# ~/.zshrc - monOS default Zsh configuration (interactive shells).
#
# The configuration lives in modules in ~/.config/zsh, sourced in this order:
#   env.zsh           PATH, EDITOR, pagers
#   options.zsh       history and shell options
#   completion.zsh    completion system
#   keybinds.zsh      key bindings (emacs mode)
#   functions/*.zsh   ffcd/ffe/ffec, y (yazi), `?` help key
#   integrations.zsh  starship, zoxide, direnv, fzf, atuin
#   plugins.zsh       autosuggestions, syntax highlighting (last plugin)
#   aliases.zsh       aliases (last, so global aliases do not leak)
#   local.zsh         your own additions (optional, not shipped)
# Accounts without ~/.config/zsh/env.zsh (root) use the modules in
# /etc/skel/.config/zsh. /root/.zshrc is a copy of this file (written by
# branding/tools/gen-themes.py).

_monos_zsh_dir="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
[[ -r $_monos_zsh_dir/env.zsh ]] || _monos_zsh_dir=/etc/skel/.config/zsh

for _monos_zsh_file in \
    "$_monos_zsh_dir"/{env,options,completion,keybinds}.zsh \
    "$_monos_zsh_dir"/functions/*.zsh(N) \
    "$_monos_zsh_dir"/{integrations,plugins,aliases}.zsh \
    "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/local.zsh"
do
    [[ -r $_monos_zsh_file ]] && source "$_monos_zsh_file"
done
unset _monos_zsh_dir _monos_zsh_file

# System information with the monOS logo: run `fastfetch` whenever you want
# (it is not started automatically). In kitty, `fastfetch -c monos-kitty`
# draws the logo as an image. Configuration: ~/.config/fastfetch/config.jsonc

# >>> monOS palette (generated by branding/tools/gen-themes.py) >>>
# fzf colors (monOS palette). Add your own options after this block.
export FZF_DEFAULT_OPTS="--color=fg:#E6E9EF,bg:-1,hl:#3D8BFF,fg+:#E6E9EF,bg+:#1A1E27,hl+:#6AA6FF,info:#9B6BFF,prompt:#B894FF,pointer:#6AA6FF,marker:#3FD68A,spinner:#22C3E6,header:#3D8BFF,border:#2E3440,gutter:-1,selected-bg:#1F3B6E"
# <<< monOS palette <<<
