" Generated by branding/tools/gen-themes.py — do not edit
" Source: branding/palette/monos.toml
" monOS colorscheme for Vim (and Neovim, which prefers colors/monos.lua).
" Uses 24-bit colors with 'termguicolors' or in gVim, and the 16 terminal
" colors otherwise (the monOS terminals use the same palette).

set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'monos'

let g:terminal_ansi_colors = ['#1A1E27', '#F2555A', '#3FD68A', '#F5C451', '#3D8BFF', '#9B6BFF', '#22C3E6', '#C8CEDA', '#737D90', '#FF7A7E', '#6BE6A6', '#FFD978', '#6AA6FF', '#B894FF', '#5CD8F0', '#F5F7FA']

hi Normal guifg=#E6E9EF guibg=#0B0D12 gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi NormalNC guifg=#E6E9EF guibg=#0B0D12 gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#0B0D12 guibg=#6AA6FF gui=NONE ctermfg=NONE ctermbg=12 cterm=NONE
hi lCursor guifg=#0B0D12 guibg=#6AA6FF gui=NONE ctermfg=NONE ctermbg=12 cterm=NONE
hi CursorIM guifg=#0B0D12 guibg=#6AA6FF gui=NONE ctermfg=NONE ctermbg=12 cterm=NONE
hi TermCursor guifg=#0B0D12 guibg=#6AA6FF gui=NONE ctermfg=NONE ctermbg=12 cterm=NONE
hi CursorLine guifg=NONE guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi CursorColumn guifg=NONE guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi ColorColumn guifg=NONE guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi CursorLineNr guifg=#E6E9EF guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi LineNr guifg=#7D8699 guibg=NONE gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
hi SignColumn guifg=#7D8699 guibg=#0B0D12 gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
hi FoldColumn guifg=#7D8699 guibg=#0B0D12 gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
hi Folded guifg=#A9B1C1 guibg=#1A1E27 gui=NONE ctermfg=7 ctermbg=0 cterm=NONE
hi VertSplit guifg=#2E3440 guibg=#0B0D12 gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
hi Visual guifg=NONE guibg=#1F3B6E gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi VisualNOS guifg=NONE guibg=#1F3B6E gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi Search guifg=#0B0D12 guibg=#F5C451 gui=NONE ctermfg=NONE ctermbg=3 cterm=NONE
hi IncSearch guifg=#0B0D12 guibg=#FFD978 gui=bold ctermfg=NONE ctermbg=11 cterm=bold
hi Substitute guifg=#0B0D12 guibg=#9B6BFF gui=NONE ctermfg=NONE ctermbg=5 cterm=NONE
hi MatchParen guifg=#FFD978 guibg=#232833 gui=bold ctermfg=11 ctermbg=0 cterm=bold
hi Pmenu guifg=#E6E9EF guibg=#232833 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi PmenuSel guifg=#FCFCFC guibg=#0C6BFA gui=bold ctermfg=15 ctermbg=4 cterm=bold
hi PmenuSbar guifg=NONE guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi PmenuThumb guifg=NONE guibg=#2E3440 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi StatusLine guifg=#E6E9EF guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi StatusLineNC guifg=#7D8699 guibg=#12151C gui=NONE ctermfg=8 ctermbg=0 cterm=NONE
hi TabLine guifg=#A9B1C1 guibg=#12151C gui=NONE ctermfg=7 ctermbg=0 cterm=NONE
hi TabLineSel guifg=#FCFCFC guibg=#0C6BFA gui=bold ctermfg=15 ctermbg=4 cterm=bold
hi TabLineFill guifg=NONE guibg=#12151C gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi WildMenu guifg=#FCFCFC guibg=#0C6BFA gui=NONE ctermfg=15 ctermbg=4 cterm=NONE
hi NonText guifg=#2E3440 guibg=NONE gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
hi SpecialKey guifg=#2E3440 guibg=NONE gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
hi EndOfBuffer guifg=#1A1E27 guibg=NONE gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
hi Whitespace guifg=#2E3440 guibg=NONE gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
hi Conceal guifg=#7D8699 guibg=NONE gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
hi Directory guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
hi Title guifg=#3D8BFF guibg=NONE gui=bold ctermfg=4 ctermbg=NONE cterm=bold
hi ErrorMsg guifg=#F2555A guibg=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
hi WarningMsg guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
hi MoreMsg guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
hi ModeMsg guifg=#E6E9EF guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi Question guifg=#22C3E6 guibg=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
hi QuickFixLine guifg=NONE guibg=#1F3B6E gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi DiffAdd guifg=NONE guibg=#143128 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi DiffDelete guifg=#F2555A guibg=#351A1F gui=NONE ctermfg=1 ctermbg=0 cterm=NONE
hi DiffChange guifg=NONE guibg=#14243D gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi DiffText guifg=NONE guibg=#1E3D6C gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
hi SpellBad guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#F2555A
hi SpellCap guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#F5C451
hi SpellRare guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#9B6BFF
hi SpellLocal guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#22C3E6
hi Comment guifg=#7D8699 guibg=NONE gui=italic ctermfg=8 ctermbg=NONE cterm=italic
hi Constant guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
hi String guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
hi Character guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
hi Number guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
hi Boolean guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
hi Float guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
hi Identifier guifg=#E6E9EF guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Function guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
hi Statement guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Conditional guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Repeat guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Label guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Operator guifg=#5CD8F0 guibg=NONE gui=NONE ctermfg=14 ctermbg=NONE cterm=NONE
hi Keyword guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Exception guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi PreProc guifg=#B894FF guibg=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Include guifg=#B894FF guibg=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Define guifg=#B894FF guibg=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Macro guifg=#B894FF guibg=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi PreCondit guifg=#B894FF guibg=NONE gui=NONE ctermfg=13 ctermbg=NONE cterm=NONE
hi Type guifg=#22C3E6 guibg=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
hi StorageClass guifg=#9B6BFF guibg=NONE gui=NONE ctermfg=5 ctermbg=NONE cterm=NONE
hi Structure guifg=#22C3E6 guibg=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
hi Typedef guifg=#22C3E6 guibg=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
hi Special guifg=#FFD978 guibg=NONE gui=NONE ctermfg=11 ctermbg=NONE cterm=NONE
hi SpecialChar guifg=#FFD978 guibg=NONE gui=NONE ctermfg=11 ctermbg=NONE cterm=NONE
hi Tag guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
hi Delimiter guifg=#A9B1C1 guibg=NONE gui=NONE ctermfg=7 ctermbg=NONE cterm=NONE
hi SpecialComment guifg=#A9B1C1 guibg=NONE gui=italic ctermfg=7 ctermbg=NONE cterm=italic
hi Debug guifg=#F2555A guibg=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
hi Underlined guifg=#22C3E6 guibg=NONE gui=underline ctermfg=6 ctermbg=NONE cterm=underline
hi Ignore guifg=#7D8699 guibg=NONE gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
hi Error guifg=#F2555A guibg=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
hi Todo guifg=#0B0D12 guibg=#F5C451 gui=bold ctermfg=NONE ctermbg=3 cterm=bold
hi Added guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
hi Changed guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
hi Removed guifg=#F2555A guibg=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
hi diffAdded guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
hi diffRemoved guifg=#F2555A guibg=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
hi diffChanged guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
if has('nvim')
  hi NormalFloat guifg=#E6E9EF guibg=#1A1E27 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
  hi FloatBorder guifg=#2E3440 guibg=#1A1E27 gui=NONE ctermfg=0 ctermbg=0 cterm=NONE
  hi FloatTitle guifg=#3D8BFF guibg=#1A1E27 gui=bold ctermfg=4 ctermbg=0 cterm=bold
  hi WinSeparator guifg=#2E3440 guibg=#0B0D12 gui=NONE ctermfg=0 ctermbg=NONE cterm=NONE
  hi CurSearch guifg=#0B0D12 guibg=#FFD978 gui=bold ctermfg=NONE ctermbg=11 cterm=bold
  hi WinBar guifg=#A9B1C1 guibg=#0B0D12 gui=bold ctermfg=7 ctermbg=NONE cterm=bold
  hi WinBarNC guifg=#7D8699 guibg=#0B0D12 gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
  hi MsgArea guifg=#E6E9EF guibg=#0B0D12 gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiagnosticError guifg=#F2555A guibg=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
  hi DiagnosticWarn guifg=#F5C451 guibg=NONE gui=NONE ctermfg=3 ctermbg=NONE cterm=NONE
  hi DiagnosticInfo guifg=#3D8BFF guibg=NONE gui=NONE ctermfg=4 ctermbg=NONE cterm=NONE
  hi DiagnosticHint guifg=#22C3E6 guibg=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
  hi DiagnosticOk guifg=#3FD68A guibg=NONE gui=NONE ctermfg=2 ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#F2555A
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#F5C451
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#3D8BFF
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#22C3E6
  hi DiagnosticUnderlineOk guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline guisp=#3FD68A
  hi DiagnosticVirtualTextError guifg=#F2555A guibg=#351A1F gui=NONE ctermfg=1 ctermbg=0 cterm=NONE
  hi DiagnosticVirtualTextWarn guifg=#F5C451 guibg=#12151C gui=NONE ctermfg=3 ctermbg=0 cterm=NONE
  hi DiagnosticVirtualTextInfo guifg=#3D8BFF guibg=#12151C gui=NONE ctermfg=4 ctermbg=0 cterm=NONE
  hi DiagnosticVirtualTextHint guifg=#22C3E6 guibg=#12151C gui=NONE ctermfg=6 ctermbg=0 cterm=NONE
  hi DiagnosticUnnecessary guifg=#7D8699 guibg=NONE gui=NONE ctermfg=8 ctermbg=NONE cterm=NONE
  hi DiagnosticDeprecated guifg=NONE guibg=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi LspReferenceText guifg=NONE guibg=#232833 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
  hi LspReferenceRead guifg=NONE guibg=#232833 gui=NONE ctermfg=NONE ctermbg=0 cterm=NONE
  hi LspReferenceWrite guifg=NONE guibg=#232833 gui=bold ctermfg=NONE ctermbg=0 cterm=bold
  hi LspInlayHint guifg=#7D8699 guibg=#12151C gui=NONE ctermfg=8 ctermbg=0 cterm=NONE
  hi LspSignatureActiveParameter guifg=NONE guibg=#1F3B6E gui=bold ctermfg=NONE ctermbg=0 cterm=bold
endif
