// Generated by branding/tools/gen-themes.py — do not edit
// Source: branding/palette/monos.toml
// monOS KSplash screen (Plasma 6): logo on the brand background with a
// thin indeterminate progress bar. `stage` goes from 1 to 6 while the
// session starts; ksplash closes the window when Plasma is ready.

import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root
    color: "#0B0D12"

    property int stage

    onStageChanged: {
        if (stage == 2) {
            introAnimation.running = true;
        }
    }

    Item {
        id: content
        anchors.fill: parent
        opacity: 0

        Image {
            id: logo
            readonly property real size: Kirigami.Units.gridUnit * 10
            anchors.centerIn: parent
            asynchronous: true
            source: "images/monos.svg"
            sourceSize.width: size
            sourceSize.height: size
        }

        // Track and moving segment of the progress indicator.
        Rectangle {
            id: track
            width: Kirigami.Units.gridUnit * 8
            height: 3
            radius: height / 2
            color: "#232833"
            clip: true
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: logo.bottom
            anchors.topMargin: Kirigami.Units.gridUnit * 2

            Rectangle {
                id: segment
                width: track.width * 0.35
                height: track.height
                radius: height / 2
                color: "#0C6BFA"

                XAnimator on x {
                    from: -segment.width
                    to: track.width
                    duration: 1400
                    loops: Animation.Infinite
                    easing.type: Easing.InOutQuad
                    // No animation when the user disabled animations.
                    running: Kirigami.Units.longDuration > 1
                }
            }
        }

        // Progress of the session start (stages 1..6) under the indicator.
        Rectangle {
            width: track.width * Math.min(root.stage, 6) / 6
            height: 1
            color: "#9B6BFF"
            opacity: 0.6
            anchors.left: track.left
            anchors.top: track.bottom
            anchors.topMargin: 4
            Behavior on width {
                NumberAnimation { duration: Kirigami.Units.longDuration }
            }
        }
    }

    OpacityAnimator {
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }
}
