# ~/.zshrc - monOS default Zsh configuration

# --- History ---
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS

# --- Completion ---
autoload -Uz compinit
compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zcompdump"
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# --- Key bindings ---
bindkey -e

# --- Tools (only initialized when installed) ---
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init zsh)"
fi
if command -v fzf >/dev/null 2>&1; then
    # Ctrl-T (files), Ctrl-R (history), Alt-C (cd)
    source <(fzf --zsh)
fi

# --- Aliases ---
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --group-directories-first --icons=auto'
    alias ll='eza -l --group-directories-first --icons=auto --git'
    alias la='eza -la --group-directories-first --icons=auto --git'
    alias lt='eza --tree --level=2 --icons=auto'
fi
if command -v bat >/dev/null 2>&1; then
    alias cat='bat --paging=never'
fi
alias lg='lazygit'

# System information with the monOS logo: run `fastfetch` whenever you want
# (it is not started automatically). In kitty, `fastfetch -c monos-kitty`
# draws the logo as an image. Configuration: ~/.config/fastfetch/config.jsonc

# >>> monOS palette (generated by branding/tools/gen-themes.py) >>>
# fzf colors (monOS palette). Add your own options after this block.
export FZF_DEFAULT_OPTS="--color=fg:#E6E9EF,bg:-1,hl:#3D8BFF,fg+:#E6E9EF,bg+:#1A1E27,hl+:#6AA6FF,info:#9B6BFF,prompt:#B894FF,pointer:#6AA6FF,marker:#3FD68A,spinner:#22C3E6,header:#3D8BFF,border:#2E3440,gutter:-1,selected-bg:#1F3B6E"
# <<< monOS palette <<<
