#!/usr/bin/env python3
"""Render every monOS theme/config file from branding/palette/monos.toml.

Usage:
    python3 branding/tools/gen-themes.py           # (re)generate all files
    python3 branding/tools/gen-themes.py --check   # only print contrast ratios

Python 3.11+ standard library only (tomllib). The output is deterministic, so
running it twice changes nothing. Files are written into the archiso overlay
(profile/airootfs) and the boot loader / installer configuration of the
profile. Fully generated files start with a "Generated by ... do not edit"
header; files that also contain hand-written parts (.zshrc, Syslinux menu,
Calamares branding) only have a marked block or specific keys rewritten.

Binary artwork (wallpapers, logos, Plymouth/GRUB/Syslinux images, GRUB fonts)
is produced by branding/tools/install-branding.sh.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PALETTE_FILE = ROOT / "branding" / "palette" / "monos.toml"
PROFILE = ROOT / "profile"
AIROOTFS = PROFILE / "airootfs"
SKEL = AIROOTFS / "etc" / "skel"
SKEL_CFG = SKEL / ".config"

GEN_NOTE = "Generated by branding/tools/gen-themes.py — do not edit"
BEGIN_MARK = ">>> monOS palette (generated by branding/tools/gen-themes.py) >>>"
END_MARK = "<<< monOS palette <<<"

ANSI_NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]

LOOK_AND_FEEL_ID = "org.monos.desktop"
COLOR_SCHEME = "MonosDark"
ICON_THEME = "yet-another-monochrome-icon-set"  # Yamis (AUR); inherits Papirus-Dark
WALLPAPER_DEFAULT = "monOS-Orbit"
KICKOFF_ICON = "monos-small"
FIXED_FONT = "JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
# UI fonts: the "Propo" variant keeps Nerd icons at their natural width, which
# reads better than single-cell icons outside a terminal grid.
UI_FONT = "JetBrainsMono Nerd Font Propo,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
SMALL_FONT = "JetBrainsMono Nerd Font Propo,8,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
TITLE_FONT = "JetBrainsMono Nerd Font Propo,10,-1,5,600,0,0,0,0,0,0,0,0,0,0,1"
PINNED_APPS = [
    "applications:kitty.desktop",
    "applications:org.kde.dolphin.desktop",
    "applications:firefox.desktop",
    "applications:code-oss.desktop",
]

# Klassy (AUR "klassy"): Qt style key from kstyle/breeze.json ("Keys": ["Klassy"]),
# decoration plugin org.kde.klassy (kdecoration/CMakeLists.txt OUTPUT_NAME)
# with theme "Klassy" (Klassy's own look-and-feel defaults).
WIDGET_STYLE = "Klassy"
DECORATION_LIBRARY = "org.kde.klassy"
DECORATION_THEME = "Klassy"
# Bibata (AUR "bibata-cursor-theme-bin"): white cursor, visible on the dark UI.
CURSOR_THEME = "Bibata-Modern-Ice"
CURSOR_SIZE = 24
# < 1 makes every Plasma/KWin animation faster (1.0 = Plasma default).
ANIMATION_DURATION_FACTOR = 0.7
VIRTUAL_DESKTOPS = 4
# Krohnkite has no "toggle tiling" action of its own (and only registers its
# shortcuts while loaded), so monos-tiling-toggle enables/disables the KWin
# script. Meta+T is taken by KWin's tiles editor and Krohnkite's Tile Layout.
TILING_TOGGLE_SHORTCUT = "Meta+Shift+T"
# Application launch shortcuts (Plasma 6 "services" components of kglobalaccel).
# Dolphin already ships X-KDE-Shortcuts=Meta+E in org.kde.dolphin.desktop.
APP_SHORTCUTS = {
    "kitty.desktop": "Meta+Return",
    "firefox.desktop": "Meta+B",
}
# KWin receives Meta+Shift+<digit> as Meta+<shifted symbol of the layout>
# (Xkb::modifiersRelevantForGlobalShortcuts drops the consumed Shift), so the
# symbols of the common layouts are bound: us / es / latam.
SHIFTED_DIGITS = {
    1: ["!"],
    2: ["@", '"'],
    3: ["#", "·"],
    4: ["$"],
}
VSCODE_EXTENSION = "monos-theme"
VSCODE_THEME_NAME = "monOS"


# --------------------------------------------------------------------------
# Palette helpers
# --------------------------------------------------------------------------
class Palette:
    def __init__(self, data: dict):
        self.data = data
        self.brand = data["brand"]
        self.ui = data["ui"]
        self.ansi = data["ansi"]
        for section in ("brand", "ui", "ansi"):
            for key, value in data[section].items():
                if not re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
                    raise SystemExit(f"error: {section}.{key} = {value!r} is not #RRGGBB")

    def ansi16(self) -> list[str]:
        normal = [self.ansi[n] for n in ANSI_NAMES]
        bright = [self.ansi[f"bright-{n}"] for n in ANSI_NAMES]
        return normal + bright

    def __getitem__(self, key: str) -> str:
        """Look up 'ui.fg', 'ansi.red', 'brand.blue'."""
        section, name = key.split(".", 1)
        return self.data[section][name]


def rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def kde_rgb(hex_color: str) -> str:
    return ",".join(str(c) for c in rgb(hex_color))


def bare(hex_color: str) -> str:
    return hex_color.lstrip("#").lower()


def mix(a: str, b: str, t: float) -> str:
    ra, ga, ba = rgb(a)
    rb, gb, bb = rgb(b)
    return "#{:02X}{:02X}{:02X}".format(
        round(ra + (rb - ra) * t), round(ga + (gb - ga) * t), round(ba + (bb - ba) * t)
    )


def luminance(hex_color: str) -> float:
    def channel(c: int) -> float:
        c = c / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = rgb(hex_color)
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def contrast(a: str, b: str) -> float:
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


# --------------------------------------------------------------------------
# Output helpers
# --------------------------------------------------------------------------
WRITTEN: list[Path] = []
CHANGED: list[Path] = []


def write(path: Path, content: str) -> None:
    if not content.endswith("\n"):
        content += "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8")
        CHANGED.append(path)
    WRITTEN.append(path)


def header(prefix: str, extra: str = "") -> str:
    lines = [f"{prefix} {GEN_NOTE}", f"{prefix} Source: branding/palette/monos.toml"]
    if extra:
        lines += [f"{prefix} {line}" if line else prefix for line in extra.splitlines()]
    return "\n".join(lines) + "\n"


def replace_block(text: str, block: str, prefix: str = "#") -> str:
    """Replace (or append) the generated block delimited by the markers."""
    begin = f"{prefix} {BEGIN_MARK}"
    end = f"{prefix} {END_MARK}"
    new = f"{begin}\n{block.rstrip()}\n{end}"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if pattern.search(text):
        return pattern.sub(lambda _m: new, text)
    return text.rstrip("\n") + "\n\n" + new + "\n"


# --------------------------------------------------------------------------
# Contrast report
# --------------------------------------------------------------------------
def contrast_report(p: Palette) -> tuple[list[str], bool]:
    bg = p.ui["bg"]
    rows = []
    ok = True
    checks = [
        ("ui.fg", 7.0),
        ("ui.fg-dim", 4.5),
        ("ui.muted", 4.5),
        ("ui.accent-text", 4.5),
        ("ui.violet-text", 4.5),
    ]
    checks += [(f"ansi.{n}", 4.5) for n in ANSI_NAMES if n != "black"]
    checks += [(f"ansi.bright-{n}", 4.5) for n in ANSI_NAMES]
    for key, target in checks:
        ratio = contrast(p[key], bg)
        passed = ratio >= target
        ok &= passed
        rows.append(f"  {key:22} {p[key]}  {ratio:5.2f}:1  (>= {target}) {'ok' if passed else 'FAIL'}")
    pairs = [
        ("ui.accent-fg on ui.accent", p.ui["accent-fg"], p.ui["accent"], 4.5),
        ("ui.fg on ui.selection", p.ui["fg"], p.ui["selection"], 7.0),
        ("ui.fg on ui.surface2", p.ui["fg"], p.ui["surface2"], 7.0),
        ("ui.fg-dim on ui.surface2", p.ui["fg-dim"], p.ui["surface2"], 4.5),
        ("ui.fg on ui.overlay", p.ui["fg"], p.ui["overlay"], 7.0),
        ("brand.blue on ui.bg (non-text)", p.brand["blue"], bg, 3.0),
    ]
    for label, fg, back, target in pairs:
        ratio = contrast(fg, back)
        passed = ratio >= target
        ok &= passed
        rows.append(f"  {label:34} {ratio:5.2f}:1  (>= {target}) {'ok' if passed else 'FAIL'}")
    return rows, ok


# --------------------------------------------------------------------------
# Terminals
# --------------------------------------------------------------------------
def gen_kitty(p: Palette) -> None:
    u, a = p.ui, p.ansi16()
    colors = "\n".join(
        f"# {name}{' (bright)' if i >= 8 else ''}\ncolor{i:<2} {a[i]}"
        for i, name in enumerate(ANSI_NAMES * 2)
    )
    content = f"""{header('#')}# monOS kitty configuration

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

window_padding_width 6
confirm_os_window_close 0
enable_audio_bell no
cursor_shape beam
cursor_trail 1

# Translucent background. background_blur enables the blur of the compositor
# on Wayland when it supports the background blur protocol (KWin does); the
# blur strength is then set by the compositor, not by this value.
background_opacity 0.92
background_blur    24

# --- Tabs (bottom, slanted powerline; ":N:" = number of windows in a tab) ---
tab_bar_edge        bottom
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template  {{title}}{{' :{{}}:'.format(num_windows) if num_windows > 1 else ''}}

# --- Remote control ---
# Only through the per-instance socket below (kitten @, some image/preview
# helpers), never through escape sequences printed by programs. Tradeoff: any
# process of your user can control this kitty (open windows, send text).
# Set allow_remote_control to no if you do not need it.
allow_remote_control socket-only
listen_on            unix:/tmp/kitty-{{kitty_pid}}

# --- Colors ---
foreground            {u['fg']}
background            {u['bg']}
selection_foreground  {u['fg']}
selection_background  {u['selection']}
cursor                {u['cursor']}
cursor_text_color     {u['bg']}
url_color             {p.ansi['cyan']}

active_border_color   {u['accent']}
inactive_border_color {u['border']}
bell_border_color     {p.ansi['yellow']}

tab_bar_background      {u['surface']}
active_tab_foreground   {u['accent-fg']}
active_tab_background   {u['accent']}
inactive_tab_foreground {u['fg-dim']}
inactive_tab_background {u['surface2']}

mark1_foreground {u['bg']}
mark1_background {p.ansi['blue']}
mark2_foreground {u['bg']}
mark2_background {p.ansi['magenta']}
mark3_foreground {u['bg']}
mark3_background {p.ansi['yellow']}

{colors}
"""
    write(SKEL_CFG / "kitty" / "kitty.conf", content)


def gen_foot(p: Palette) -> None:
    u, a = p.ui, p.ansi16()
    regular = "\n".join(f"regular{i}={bare(a[i])}  # {ANSI_NAMES[i]}" for i in range(8))
    bright = "\n".join(f"bright{i}={bare(a[i + 8])}  # bright {ANSI_NAMES[i]}" for i in range(8))
    content = f"""{header('#')}# monOS foot configuration (fallback terminal: works without OpenGL).

[main]
font=JetBrainsMono Nerd Font:size=11
pad=8x8

[cursor]
style=beam

[colors-dark]
alpha=0.95
background={bare(u['bg'])}
foreground={bare(u['fg'])}
cursor={bare(u['bg'])} {bare(u['cursor'])}
selection-foreground={bare(u['fg'])}
selection-background={bare(u['selection'])}
jump-labels={bare(u['bg'])} {bare(p.ansi['yellow'])}
scrollback-indicator={bare(u['accent-fg'])} {bare(u['accent'])}
search-box-no-match={bare(u['bg'])} {bare(p.ansi['red'])}
search-box-match={bare(u['bg'])} {bare(p.ansi['yellow'])}
urls={bare(p.ansi['cyan'])}
{regular}
{bright}
"""
    write(SKEL_CFG / "foot" / "foot.ini", content)


# --------------------------------------------------------------------------
# CLI tools
# --------------------------------------------------------------------------
def gen_btop(p: Palette) -> None:
    u, x = p.ui, p.ansi
    theme = {
        "main_bg": u["bg"],
        "main_fg": u["fg"],
        "title": u["fg"],
        "hi_fg": x["blue"],
        "selected_bg": u["selection"],
        "selected_fg": u["fg"],
        "inactive_fg": u["muted"],
        "graph_text": u["fg-dim"],
        "meter_bg": u["overlay"],
        "proc_misc": x["cyan"],
        "cpu_box": u["accent"],
        "mem_box": u["violet"],
        "net_box": x["cyan"],
        "proc_box": u["border"],
        "div_line": u["border"],
        "temp_start": x["green"],
        "temp_mid": x["yellow"],
        "temp_end": x["red"],
        "cpu_start": x["blue"],
        "cpu_mid": x["magenta"],
        "cpu_end": x["bright-magenta"],
        "free_start": x["green"],
        "free_mid": x["green"],
        "free_end": x["bright-green"],
        "cached_start": x["cyan"],
        "cached_mid": x["cyan"],
        "cached_end": x["bright-cyan"],
        "available_start": x["blue"],
        "available_mid": x["blue"],
        "available_end": x["bright-blue"],
        "used_start": x["magenta"],
        "used_mid": x["red"],
        "used_end": x["bright-red"],
        "download_start": x["blue"],
        "download_mid": x["cyan"],
        "download_end": x["bright-cyan"],
        "upload_start": x["magenta"],
        "upload_mid": x["bright-magenta"],
        "upload_end": x["bright-red"],
        "process_start": x["blue"],
        "process_mid": x["magenta"],
        "process_end": x["red"],
        "proc_banner_bg": u["accent"],
        "proc_banner_fg": u["accent-fg"],
        "proc_follow_bg": u["selection"],
        "proc_pause_bg": u["overlay"],
        "followed_bg": u["selection"],
        "followed_fg": u["fg"],
    }
    body = "\n".join(f'theme[{k}]="{v}"' for k, v in theme.items())
    write(SKEL_CFG / "btop" / "themes" / "monos.theme", f"{header('#')}# monOS theme for btop\n\n{body}\n")
    # btop keeps unknown options at their defaults and rewrites this file on
    # exit with the full option list, keeping these values.
    conf = f"""{header('#')}# Minimal btop configuration: every other option keeps its default.
color_theme = "monos"
theme_background = True
truecolor = True
rounded_corners = True
"""
    write(SKEL_CFG / "btop" / "btop.conf", conf)


def gen_yazi(p: Palette) -> None:
    u, x = p.ui, p.ansi
    content = f"""{header('#')}# monOS theme for yazi: only the colors differ from the built-in dark preset.

[mgr]
cwd = {{ fg = "{x['cyan']}" }}
find_keyword  = {{ fg = "{x['yellow']}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{x['magenta']}", bg = "reset", bold = true, italic = true }}
marker_copied   = {{ fg = "{x['green']}", bg = "{x['green']}" }}
marker_cut      = {{ fg = "{x['red']}", bg = "{x['red']}" }}
marker_marked   = {{ fg = "{x['cyan']}", bg = "{x['cyan']}" }}
marker_selected = {{ fg = "{x['yellow']}", bg = "{x['yellow']}" }}
count_copied   = {{ fg = "{u['bg']}", bg = "{x['green']}" }}
count_cut      = {{ fg = "{u['bg']}", bg = "{x['red']}" }}
count_selected = {{ fg = "{u['bg']}", bg = "{x['yellow']}" }}
border_style  = {{ fg = "{u['border']}" }}

[indicator]
parent  = {{ fg = "{u['fg']}", bg = "{u['surface2']}" }}
current = {{ fg = "{u['accent-fg']}", bg = "{u['selection']}", bold = true }}
preview = {{ underline = true }}

[tabs]
active   = {{ fg = "{u['accent-fg']}", bg = "{u['accent']}", bold = true }}
inactive = {{ fg = "{u['fg-dim']}", bg = "{u['surface2']}" }}

[mode]
normal_main = {{ fg = "{u['accent-fg']}", bg = "{u['accent']}", bold = true }}
normal_alt  = {{ fg = "{x['blue']}", bg = "{u['surface2']}" }}
select_main = {{ fg = "{u['bg']}", bg = "{x['magenta']}", bold = true }}
select_alt  = {{ fg = "{x['magenta']}", bg = "{u['surface2']}" }}
unset_main  = {{ fg = "{u['bg']}", bg = "{x['red']}", bold = true }}
unset_alt   = {{ fg = "{x['red']}", bg = "{u['surface2']}" }}

[status]
perm_sep   = {{ fg = "{u['muted']}" }}
perm_type  = {{ fg = "{x['green']}" }}
perm_read  = {{ fg = "{x['yellow']}" }}
perm_write = {{ fg = "{x['red']}" }}
perm_exec  = {{ fg = "{x['cyan']}" }}
progress_label  = {{ fg = "{u['fg']}", bold = true }}
progress_normal = {{ fg = "{x['blue']}", bg = "{u['surface2']}" }}
progress_error  = {{ fg = "{x['red']}", bg = "{u['surface2']}" }}

[which]
border          = {{ fg = "{u['accent']}" }}
cand            = {{ fg = "{x['cyan']}" }}
rest            = {{ fg = "{u['muted']}" }}
desc            = {{ fg = "{x['magenta']}" }}
separator_style = {{ fg = "{u['muted']}" }}

[confirm]
border = {{ fg = "{u['accent']}" }}
title  = {{ fg = "{x['blue']}" }}

[spot]
border   = {{ fg = "{u['accent']}" }}
title    = {{ fg = "{x['blue']}" }}
tbl_col  = {{ fg = "{x['blue']}" }}
tbl_cell = {{ fg = "{x['yellow']}", reversed = true }}

[notify]
title_info  = {{ fg = "{x['green']}" }}
title_warn  = {{ fg = "{x['yellow']}" }}
title_error = {{ fg = "{x['red']}" }}

[pick]
border = {{ fg = "{u['accent']}" }}
active = {{ fg = "{x['magenta']}", bold = true }}

[input]
border   = {{ fg = "{u['accent']}" }}
selected = {{ bg = "{u['selection']}" }}

[cmp]
border = {{ fg = "{u['accent']}" }}
active = {{ bg = "{u['selection']}" }}

[tasks]
border  = {{ fg = "{u['accent']}" }}
hovered = {{ fg = "{x['magenta']}", bold = true }}

[help]
border  = {{ fg = "{u['accent']}" }}
chord   = {{ fg = "{x['cyan']}" }}
hovered = {{ bg = "{u['selection']}", bold = true }}
"""
    write(SKEL_CFG / "yazi" / "theme.toml", content)
    gen_yazi_init(p)


def gen_yazi_init(p: Palette) -> None:
    """yazi init.lua: plugin setup; the yatline bars use the monOS palette.

    yazi.toml, keymap.toml and the vendored plugins in plugins/ are plain
    files (no colors); see plugins/monos-plugins.txt.
    """
    u, x = p.ui, p.ansi
    content = f"""{header('--')}-- monOS yazi plugin setup. Every plugin is vendored in ./plugins (pinned
-- versions and licenses: plugins/monos-plugins.txt); nothing is downloaded.
-- Plugins that only run from a key or as previewers (bypass, clipboard,
-- lazygit, mediainfo, mount, ouch, piper) need no setup here.

-- Full border around the three panes.
require("full-border"):setup({{ type = ui.Border.PLAIN }})

-- Header line (tabs, clock) and status line (mode, size, name, position,
-- permissions) in the monOS colors.
require("yatline"):setup({{
\tsection_separator = {{ open = "\\u{{e0b6}}", close = "\\u{{e0b4}}" }},
\tpart_separator = {{ open = "\\u{{e0b7}}", close = "\\u{{e0b5}}" }},
\tinverse_separator = {{ open = "\\u{{e0d6}}", close = "\\u{{e0d7}}" }},
\tpadding = {{ inner = 1, outer = 1 }},

\tstyle_a = {{
\t\tfg = "{u['accent-fg']}",
\t\tbg_mode = {{ normal = "{u['accent']}", select = "{u['violet']}", un_set = "{x['red']}" }},
\t}},
\tstyle_b = {{ bg = "{u['overlay']}", fg = "{u['fg']}" }},
\tstyle_c = {{ bg = "{u['surface2']}", fg = "{u['fg-dim']}" }},

\tpermissions_t_fg = "{x['green']}",
\tpermissions_r_fg = "{x['yellow']}",
\tpermissions_w_fg = "{x['red']}",
\tpermissions_x_fg = "{x['cyan']}",
\tpermissions_s_fg = "{u['muted']}",

\ttab_width = 20,

\tselected = {{ icon = "\\u{{f0eed}}", fg = "{x['yellow']}" }},
\tcopied = {{ icon = "\\u{{f4bb}}", fg = "{x['green']}" }},
\tcut = {{ icon = "\\u{{f0c4}}", fg = "{x['red']}" }},
\tfiles = {{ icon = "\\u{{f15b}}", fg = "{x['blue']}" }},
\tfiltereds = {{ icon = "\\u{{f0b0}}", fg = "{x['magenta']}" }},

\ttotal = {{ icon = "\\u{{f0b8d}}", fg = "{x['yellow']}" }},
\tsuccess = {{ icon = "\\u{{f00c}}", fg = "{x['green']}" }},
\tfailed = {{ icon = "\\u{{f00d}}", fg = "{x['red']}" }},

\tshow_background = false,
\tdisplay_header_line = true,
\tdisplay_status_line = true,
\tcomponent_positions = {{ "header", "tab", "status" }},

\theader_line = {{
\t\tleft = {{
\t\t\tsection_a = {{ {{ type = "line", custom = false, name = "tabs", params = {{ "left" }} }} }},
\t\t\tsection_b = {{}},
\t\t\tsection_c = {{}},
\t\t}},
\t\tright = {{
\t\t\tsection_a = {{ {{ type = "string", custom = false, name = "date", params = {{ "%H:%M" }} }} }},
\t\t\tsection_b = {{}},
\t\t\tsection_c = {{}},
\t\t}},
\t}},

\tstatus_line = {{
\t\tleft = {{
\t\t\tsection_a = {{ {{ type = "string", custom = false, name = "tab_mode" }} }},
\t\t\tsection_b = {{ {{ type = "string", custom = false, name = "hovered_size" }} }},
\t\t\tsection_c = {{
\t\t\t\t{{ type = "string", custom = false, name = "hovered_name" }},
\t\t\t\t{{ type = "coloreds", custom = false, name = "count" }},
\t\t\t}},
\t\t}},
\t\tright = {{
\t\t\tsection_a = {{ {{ type = "string", custom = false, name = "cursor_position" }} }},
\t\t\tsection_b = {{ {{ type = "string", custom = false, name = "cursor_percentage" }} }},
\t\t\tsection_c = {{
\t\t\t\t-- params = false: the icon variant calls the deprecated File:icon().
\t\t\t\t{{ type = "string", custom = false, name = "hovered_file_extension", params = {{ false }} }},
\t\t\t\t{{ type = "coloreds", custom = false, name = "permissions" }},
\t\t\t}},
\t\t}},
\t}},
}})

-- Vim-style counts: 3j, 5k, 2gg (1-9 start a motion). Relative line numbers.
require("relative-motions"):setup({{ show_numbers = "relative_absolute", show_motion = true }})

-- fg (f g / f G / f f): search file contents or names with ripgrep + fzf and
-- jump to the result in yazi.
require("fg"):setup({{ default_action = "jump" }})

-- what-size (Ctrl-S): size of the selection or of the current directory.
require("what-size"):setup({{}})

if ya.uid then
\t-- gvfs (M m / M u / g m ...): mount phones (MTP), SMB/SFTP shares, ... through
\t-- GVFS. Needs a D-Bus session (any desktop login).
\trequire("gvfs"):setup({{
\t\twhich_keys = "1234567890qwertyuiopasdfghjklzxcvbnm",
\t\tblacklist_devices = {{ {{ scheme = "file" }} }},
\t\tsave_path = os.getenv("HOME") .. "/.config/yazi/gvfs.private",
\t\tsave_path_automounts = os.getenv("HOME") .. "/.config/yazi/gvfs_automounts.private",
\t\tinput_position = {{ "center", y = 0, w = 60 }},
\t}})

\t-- recycle-bin (R b / R o / R r / R d / R e): browse and restore the trash
\t-- (trash-cli).
\trequire("recycle-bin"):setup()
end
"""
    write(SKEL_CFG / "yazi" / "init.lua", content)


def gen_bat() -> None:
    content = f"""{header('#')}# bat uses the terminal's 16 ANSI colors, so it follows the monOS terminal
# palette without a custom theme (no `bat cache --build` needed).
--theme=ansi
"""
    write(SKEL_CFG / "bat" / "config", content)


def gen_lazygit(p: Palette) -> None:
    u, x = p.ui, p.ansi
    content = f"""{header('#')}gui:
  theme:
    activeBorderColor:
      - "{u['accent']}"
      - bold
    inactiveBorderColor:
      - "{u['border']}"
    searchingActiveBorderColor:
      - "{x['cyan']}"
      - bold
    optionsTextColor:
      - "{x['blue']}"
    selectedLineBgColor:
      - "{u['selection']}"
    inactiveViewSelectedLineBgColor:
      - "{u['surface2']}"
    cherryPickedCommitFgColor:
      - "{x['blue']}"
    cherryPickedCommitBgColor:
      - "{u['surface2']}"
    markedBaseCommitFgColor:
      - "{x['yellow']}"
    markedBaseCommitBgColor:
      - "{u['surface2']}"
    unstagedChangesColor:
      - "{x['red']}"
    defaultFgColor:
      - default
"""
    write(SKEL_CFG / "lazygit" / "config.yml", content)


def gen_zellij(p: Palette) -> None:
    u, x = p.ui, p.ansi
    content = f"""{header('//')}// Only the theme is set here; every other option keeps zellij's default.
theme "monos"

themes {{
    monos {{
        fg "{u['fg']}"
        bg "{u['surface2']}"
        black "{u['bg']}"
        red "{x['red']}"
        green "{x['green']}"
        yellow "{x['yellow']}"
        blue "{u['accent']}"
        magenta "{x['magenta']}"
        cyan "{x['cyan']}"
        white "{x['white']}"
        orange "{x['bright-yellow']}"
    }}
}}
"""
    write(SKEL_CFG / "zellij" / "config.kdl", content)


# Right-prompt language/tool modules: (module, short label, Nerd Font symbol,
# palette color). Each one is only shown inside a matching project.
STARSHIP_LANGS = [
    ("c", "c", "", "bright_cyan"),
    ("cpp", "cpp", "", "bright_cyan"),
    ("cmake", "cmake", "", "bright_blue"),
    ("golang", "go", "", "bright_cyan"),
    ("rust", "rs", "\U000f1617", "bright_red"),
    ("python", "py", "", "bright_yellow"),
    ("nodejs", "node", "", "bright_green"),
    ("java", "java", "", "bright_red"),
    ("kotlin", "kt", "", "bright_violet"),
    ("lua", "lua", "", "bright_blue"),
    ("php", "php", "", "violet"),
    ("ruby", "rb", "", "red"),
    ("dotnet", ".net", "", "violet"),
    ("docker_context", "docker", "", "blue"),
    ("nix_shell", "nix", "", "bright_blue"),
    ("aws", "aws", "", "yellow"),
]


def gen_starship(p: Palette) -> None:
    u, x = p.ui, p.ansi
    right = "".join(f"${m}" for m, *_ in STARSHIP_LANGS)
    lang_blocks = []
    for module, label, symbol, color in STARSHIP_LANGS:
        lines = [f"[{module}]", f'symbol = "{symbol} "', f'style = "bold {color}"']
        if module == "python":
            # Show the virtualenv and the version: they matter in Python.
            lines.append('format = " [py](italic muted) [${symbol}(\\\\($virtualenv\\\\) )${version}]($style)"')
            lines.append('version_format = "${raw}"')
        elif module == "docker_context":
            lines.append('format = " [docker](italic muted) [$symbol$context]($style)"')
        elif module == "nix_shell":
            lines.append('format = " [nix](italic muted) [$symbol$state( $name)]($style)"')
        elif module == "aws":
            lines.append('format = " [aws](italic muted) [$symbol$profile( $region)]($style)"')
            lines.append("disabled = true")
        else:
            lines.append(f'format = " [{label}](italic muted) [$symbol]($style)"')
        if module == "nodejs":
            # A package.json (or lock file / node_modules) marks a Node project;
            # loose .js files do not.
            lines.append("detect_extensions = []")
            lines.append('detect_files = ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", ".nvmrc"]')
            lines.append('detect_folders = ["node_modules"]')
        lang_blocks.append("\n".join(lines))
    langs = "\n\n".join(lang_blocks)
    content = f"""{header('#')}# monOS Starship prompt (one line):
#   left:  distro glyph, directory, git branch/commit/state/status, prompt character
#   right: language/tool of the current project (label + icon), memory (only
#          above 75 %), duration of slow commands, exit status of failed
#          commands, time
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "monos"
continuation_prompt = "[▶▶ ](muted)"

format = "[\\U000f08c7 ](bold blue)$directory$git_branch$git_commit$git_state$git_status$character"
right_format = "{right}$memory_usage$cmd_duration$status$time"

[palettes.monos]
blue = "{x['blue']}"
bright_blue = "{x['bright-blue']}"
violet = "{u['violet-text']}"
bright_violet = "{x['bright-magenta']}"
cyan = "{x['cyan']}"
bright_cyan = "{x['bright-cyan']}"
green = "{x['green']}"
bright_green = "{x['bright-green']}"
yellow = "{x['yellow']}"
bright_yellow = "{x['bright-yellow']}"
red = "{x['red']}"
bright_red = "{x['bright-red']}"
muted = "{u['muted']}"
fg_dim = "{u['fg-dim']}"
fg = "{u['fg']}"

[directory]
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "\\ue0a0 "
style = "bold violet"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_commit]
style = "bold green"
format = "[\\\\($hash$tag\\\\)]($style) "

[git_state]
style = "bold yellow"

[git_status]
style = "bold cyan"
ahead = "⇡${{count}}"
behind = "⇣${{count}}"
diverged = "⇕⇡${{ahead_count}}⇣${{behind_count}}"
format = "([$all_status$ahead_behind]($style) )"

[character]
success_symbol = "[❯](bold bright_blue)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

{langs}

[memory_usage]
disabled = false
threshold = 75
symbol = "\\U000f035b "
style = "bold bright_cyan"
format = " [mem](italic muted) [$symbol$ram( | $swap)]($style)"

[cmd_duration]
min_time = 2000
style = "bold yellow"
format = " [\\uf252 $duration]($style)"

[status]
disabled = false
symbol = "\\uf00d "
style = "bold red"
format = " [$symbol$status]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg_dim"
format = " [\\uf43a $time]($style)"
"""
    write(SKEL_CFG / "starship.toml", content)


def gen_zshrc(p: Palette) -> None:
    u, x = p.ui, p.ansi
    colors = ",".join(
        [
            f"fg:{u['fg']}",
            "bg:-1",
            f"hl:{x['blue']}",
            f"fg+:{u['fg']}",
            f"bg+:{u['surface2']}",
            f"hl+:{x['bright-blue']}",
            f"info:{x['magenta']}",
            f"prompt:{x['bright-magenta']}",
            f"pointer:{u['cursor']}",
            f"marker:{x['green']}",
            f"spinner:{x['cyan']}",
            f"header:{x['blue']}",
            f"border:{u['border']}",
            f"gutter:-1",
            f"selected-bg:{u['selection']}",
        ]
    )
    block = f"""# fzf colors (monOS palette). Add your own options after this block.
export FZF_DEFAULT_OPTS="--color={colors}"
"""
    path = SKEL / ".zshrc"
    text = path.read_text(encoding="utf-8")
    text = replace_block(text, block)
    write(path, text)
    # root has no ~/.config/zsh: the same .zshrc falls back to the modules in
    # /etc/skel/.config/zsh, so /root/.zshrc is an exact copy.
    write(AIROOTFS / "root" / ".zshrc", text)


def gen_helix(p: Palette) -> None:
    u, x = p.ui, p.ansi
    theme = f"""{header('#')}# monOS theme for Helix.

"attribute" = "yellow"
"comment" = {{ fg = "muted", modifiers = ["italic"] }}
"constant" = "yellow"
"constant.numeric" = "yellow"
"constant.builtin" = "yellow"
"constant.character.escape" = "bright-yellow"
"constructor" = "cyan"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "bright-violet"
"keyword" = "violet"
"keyword.control.import" = "bright-violet"
"keyword.directive" = "bright-violet"
"keyword.operator" = "violet"
"label" = "violet"
"namespace" = "cyan"
"operator" = "bright-cyan"
"punctuation" = "fg-dim"
"special" = "bright-yellow"
"string" = "green"
"string.regexp" = "bright-yellow"
"tag" = "blue"
"type" = "cyan"
"type.builtin" = "cyan"
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg"
"variable.other.member" = "bright-blue"

"markup.heading" = {{ fg = "blue", modifiers = ["bold"] }}
"markup.raw" = "green"
"markup.bold" = {{ modifiers = ["bold"] }}
"markup.italic" = {{ modifiers = ["italic"] }}
"markup.strikethrough" = {{ modifiers = ["crossed_out"] }}
"markup.list" = "violet"
"markup.quote" = {{ fg = "fg-dim", modifiers = ["italic"] }}
"markup.link.url" = {{ fg = "cyan", modifiers = ["underlined"] }}
"markup.link.text" = "blue"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"diagnostic.error" = {{ underline = {{ color = "red", style = "curl" }} }}
"diagnostic.warning" = {{ underline = {{ color = "yellow", style = "curl" }} }}
"diagnostic.info" = {{ underline = {{ color = "blue", style = "curl" }} }}
"diagnostic.hint" = {{ underline = {{ color = "cyan", style = "curl" }} }}
"diagnostic.unnecessary" = {{ modifiers = ["dim"] }}
"diagnostic.deprecated" = {{ modifiers = ["crossed_out"] }}
"error" = "red"
"warning" = "yellow"
"info" = "blue"
"hint" = "cyan"

"ui.background" = {{ bg = "bg" }}
"ui.text" = "fg"
"ui.text.focus" = {{ fg = "fg", modifiers = ["bold"] }}
"ui.text.inactive" = "muted"
"ui.linenr" = "muted"
"ui.linenr.selected" = {{ fg = "fg", modifiers = ["bold"] }}
"ui.cursor" = {{ fg = "bg", bg = "fg-dim" }}
"ui.cursor.primary" = {{ fg = "bg", bg = "cursor" }}
"ui.cursor.match" = {{ bg = "overlay", modifiers = ["bold"] }}
"ui.cursorline.primary" = {{ bg = "surface2" }}
"ui.selection" = {{ bg = "overlay" }}
"ui.selection.primary" = {{ bg = "selection" }}
"ui.statusline" = {{ fg = "fg", bg = "surface2" }}
"ui.statusline.inactive" = {{ fg = "muted", bg = "surface" }}
"ui.statusline.normal" = {{ fg = "accent-fg", bg = "accent", modifiers = ["bold"] }}
"ui.statusline.insert" = {{ fg = "bg", bg = "green", modifiers = ["bold"] }}
"ui.statusline.select" = {{ fg = "bg", bg = "violet", modifiers = ["bold"] }}
"ui.popup" = {{ fg = "fg", bg = "overlay" }}
"ui.window" = "border"
"ui.help" = {{ fg = "fg", bg = "overlay" }}
"ui.menu" = {{ fg = "fg", bg = "overlay" }}
"ui.menu.selected" = {{ fg = "accent-fg", bg = "accent" }}
"ui.menu.scroll" = {{ fg = "muted", bg = "surface2" }}
"ui.virtual.whitespace" = "border"
"ui.virtual.indent-guide" = "border"
"ui.virtual.ruler" = {{ bg = "surface2" }}
"ui.virtual.inlay-hint" = "muted"
"ui.virtual.jump-label" = {{ fg = "yellow", modifiers = ["bold"] }}
"ui.highlight" = {{ bg = "surface2" }}
"ui.gutter" = {{ bg = "bg" }}
"ui.bufferline" = {{ fg = "fg-dim", bg = "surface" }}
"ui.bufferline.active" = {{ fg = "accent-fg", bg = "accent" }}

[palette]
bg = "{u['bg']}"
surface = "{u['surface']}"
surface2 = "{u['surface2']}"
overlay = "{u['overlay']}"
border = "{u['border']}"
fg = "{u['fg']}"
fg-dim = "{u['fg-dim']}"
muted = "{u['muted']}"
selection = "{u['selection']}"
accent = "{u['accent']}"
accent-fg = "{u['accent-fg']}"
cursor = "{u['cursor']}"
red = "{x['red']}"
green = "{x['green']}"
yellow = "{x['yellow']}"
bright-yellow = "{x['bright-yellow']}"
blue = "{x['blue']}"
bright-blue = "{x['bright-blue']}"
violet = "{u['violet-text']}"
bright-violet = "{x['bright-magenta']}"
cyan = "{x['cyan']}"
bright-cyan = "{x['bright-cyan']}"
"""
    write(SKEL_CFG / "helix" / "themes" / "monos.toml", theme)
    write(SKEL_CFG / "helix" / "config.toml", f'{header("#")}theme = "monos"\n')


# --------------------------------------------------------------------------
# fastfetch
# --------------------------------------------------------------------------
# $1 = outline (fg), $2 = eyes (brand blue). Every line is padded to the same
# width so the info column lines up.
MONKEY = [
    '               .--.',
    '          .-""`    `""-.',
    '        .\'   .-""""-.   \'.',
    "  .-.  /   .'        '.   \\  .-.",
    ' /   \\|   /  .-.  .-.  \\   |/   \\',
    '|  (  |  |  ( $2@$1 )( $2@$1 )  |  |  )  |',
    " \\   /|  |   '-'  '-'   |  |\\   /",
    "  '-'  \\  \\     ..     /  /  '-'",
    "        \\  '.  \\__/  .'  /",
    "         '.  '------'  .'",
    "           '-.______.-'",
]

BOX_TOP = "┌──────────────────────────────────────────┐"
BOX_BOTTOM = "└──────────────────────────────────────────┘"


def fastfetch_modules(p: Palette) -> list:
    """Two boxes: system/session, then user@host and hardware."""
    x = p.ansi
    box = p.ui["border"]

    def m(kind: str, key: str, color: str, **extra) -> dict:
        return {"type": kind, "key": key, "keyColor": x[color], **extra}

    return [
        {"type": "custom", "format": BOX_TOP, "outputColor": box},
        m("chassis", "  \U000f01fa Chassis", "cyan", format="{type}"),
        m("os", "  \U000f08c7 OS", "blue", format="{pretty-name} {arch}"),
        m("kernel", "   Kernel", "blue", format="{release}"),
        m("packages", "  \U000f03d7 Packages", "green"),
        m("display", "  \U000f0379 Display", "green", format="{width}x{height} @ {refresh-rate}Hz"),
        m("terminal", "   Terminal", "yellow"),
        m("de", "   DE", "yellow"),
        {"type": "custom", "format": BOX_BOTTOM, "outputColor": box},
        "break",
        {"type": "title", "key": "  ", "format": "{user-name-colored}{at-symbol-colored}{host-name-colored}"},
        {"type": "custom", "format": BOX_TOP, "outputColor": box},
        m("cpu", "   CPU", "magenta", format="{name} @ {freq-max}"),
        m("gpu", "  \U000f02b4 GPU", "magenta", format="{name}"),
        m("gpu", "   GPU Driver", "magenta", format="{driver}"),
        m("memory", "  \U000f035b Memory", "cyan"),
        m("disk", "  \U000f199f OS Age", "red", folders="/", format="{days} days"),
        m("uptime", "  \U000f1ad0 Uptime", "red"),
        {"type": "custom", "format": BOX_BOTTOM, "outputColor": box},
        {"type": "colors", "paddingLeft": 2, "symbol": "circle"},
    ]


def gen_fastfetch(p: Palette) -> None:
    u, x = p.ui, p.ansi
    lines = MONKEY
    width = max(len(re.sub(r"\$\d", "", line)) for line in lines)
    art = "$1" + "\n".join(lines) + "\n"
    write(AIROOTFS / "usr" / "share" / "monos" / "fastfetch" / "monos.txt", art)
    modules = fastfetch_modules(p)

    def config(logo: dict, note: str) -> str:
        cfg = {
            "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
            "logo": logo,
            "display": {
                "separator": "  ",
                "color": {"keys": x["blue"], "title": u["accent-text"], "separator": u["muted"]},
                "key": {"width": 16},
            },
            "modules": modules,
        }
        return header("//", note) + json.dumps(cfg, indent=2, ensure_ascii=False) + "\n"

    ascii_logo = {
        "type": "file",
        "source": "/usr/share/monos/fastfetch/monos.txt",
        "color": {"1": u["fg"], "2": x["blue"]},
        "padding": {"left": 1, "right": 3, "top": 2},
    }
    kitty_logo = {
        "type": "kitty-direct",
        "source": "/usr/share/monos/fastfetch/monos.png",
        "width": width,
        "height": len(lines) + 2,
        "padding": {"left": 1, "right": 3, "top": 2},
    }
    write(
        SKEL_CFG / "fastfetch" / "config.jsonc",
        config(
            ascii_logo,
            "monOS fastfetch configuration: ASCII-art logo, works in every terminal\n"
            "(kitty, foot, the Linux console, SSH). In kitty, `fastfetch -c monos-kitty`\n"
            "shows the logo as an image (kitty graphics protocol). Icons need a Nerd Font.",
        ),
    )
    write(
        AIROOTFS / "usr" / "local" / "share" / "fastfetch" / "presets" / "monos-kitty.jsonc",
        config(
            kitty_logo,
            "monOS fastfetch preset with the logo as an image (kitty graphics protocol).\n"
            "Same modules as ~/.config/fastfetch/config.jsonc. Usage (kitty only):\n"
            "fastfetch -c monos-kitty",
        ),
    )


# --------------------------------------------------------------------------
# Neovim / Vim colorscheme
# --------------------------------------------------------------------------
def editor_groups(p: Palette) -> tuple[dict, dict]:
    """Return (common groups, nvim-only groups): name -> spec.

    spec = dict(fg=, bg=, sp=, style=[...], link=) with palette keys or hex.
    """
    u, x = p.ui, p.ansi
    c = {
        "bg": u["bg"], "surface": u["surface"], "surface2": u["surface2"],
        "overlay": u["overlay"], "border": u["border"], "fg": u["fg"],
        "fg_dim": u["fg-dim"], "muted": u["muted"], "selection": u["selection"],
        "accent": u["accent"], "accent_fg": u["accent-fg"], "cursor": u["cursor"],
        "red": x["red"], "green": x["green"], "yellow": x["yellow"], "blue": x["blue"],
        "violet": u["violet-text"], "cyan": x["cyan"], "bred": x["bright-red"],
        "bgreen": x["bright-green"], "byellow": x["bright-yellow"], "bblue": x["bright-blue"],
        "bviolet": x["bright-magenta"], "bcyan": x["bright-cyan"],
        "diff_add": mix(u["bg"], x["green"], 0.18), "diff_del": mix(u["bg"], x["red"], 0.18),
        "diff_chg": mix(u["bg"], x["blue"], 0.18), "diff_txt": mix(u["bg"], x["blue"], 0.38),
    }

    def g(fg=None, bg=None, style=None, sp=None):
        return {"fg": c.get(fg) if fg else None, "bg": c.get(bg) if bg else None,
                "style": style or [], "sp": c.get(sp) if sp else None}

    def link(target):
        return {"link": target}

    common = {
        "Normal": g("fg", "bg"),
        "NormalNC": g("fg", "bg"),
        "Cursor": g("bg", "cursor"),
        "lCursor": g("bg", "cursor"),
        "CursorIM": g("bg", "cursor"),
        "TermCursor": g("bg", "cursor"),
        "CursorLine": g(None, "surface2"),
        "CursorColumn": g(None, "surface2"),
        "ColorColumn": g(None, "surface2"),
        "CursorLineNr": g("fg", None, ["bold"]),
        "LineNr": g("muted"),
        "SignColumn": g("muted", "bg"),
        "FoldColumn": g("muted", "bg"),
        "Folded": g("fg_dim", "surface2"),
        "VertSplit": g("border", "bg"),
        "Visual": g(None, "selection"),
        "VisualNOS": g(None, "selection"),
        "Search": g("bg", "yellow"),
        "IncSearch": g("bg", "byellow", ["bold"]),
        "Substitute": g("bg", "violet"),
        "MatchParen": g("byellow", "overlay", ["bold"]),
        "Pmenu": g("fg", "overlay"),
        "PmenuSel": g("accent_fg", "accent", ["bold"]),
        "PmenuSbar": g(None, "surface2"),
        "PmenuThumb": g(None, "border"),
        "StatusLine": g("fg", "surface2"),
        "StatusLineNC": g("muted", "surface"),
        "TabLine": g("fg_dim", "surface"),
        "TabLineSel": g("accent_fg", "accent", ["bold"]),
        "TabLineFill": g(None, "surface"),
        "WildMenu": g("accent_fg", "accent"),
        "NonText": g("border"),
        "SpecialKey": g("border"),
        "EndOfBuffer": g("surface2"),
        "Whitespace": g("border"),
        "Conceal": g("muted"),
        "Directory": g("blue"),
        "Title": g("blue", None, ["bold"]),
        "ErrorMsg": g("red", None, ["bold"]),
        "WarningMsg": g("yellow"),
        "MoreMsg": g("green"),
        "ModeMsg": g("fg", None, ["bold"]),
        "Question": g("cyan"),
        "QuickFixLine": g(None, "selection"),
        "DiffAdd": g(None, "diff_add"),
        "DiffDelete": g("red", "diff_del"),
        "DiffChange": g(None, "diff_chg"),
        "DiffText": g(None, "diff_txt"),
        "SpellBad": g(None, None, ["undercurl"], "red"),
        "SpellCap": g(None, None, ["undercurl"], "yellow"),
        "SpellRare": g(None, None, ["undercurl"], "violet"),
        "SpellLocal": g(None, None, ["undercurl"], "cyan"),
        "Comment": g("muted", None, ["italic"]),
        "Constant": g("yellow"),
        "String": g("green"),
        "Character": g("green"),
        "Number": g("yellow"),
        "Boolean": g("yellow"),
        "Float": g("yellow"),
        "Identifier": g("fg"),
        "Function": g("blue"),
        "Statement": g("violet"),
        "Conditional": g("violet"),
        "Repeat": g("violet"),
        "Label": g("violet"),
        "Operator": g("bcyan"),
        "Keyword": g("violet"),
        "Exception": g("violet"),
        "PreProc": g("bviolet"),
        "Include": g("bviolet"),
        "Define": g("bviolet"),
        "Macro": g("bviolet"),
        "PreCondit": g("bviolet"),
        "Type": g("cyan"),
        "StorageClass": g("violet"),
        "Structure": g("cyan"),
        "Typedef": g("cyan"),
        "Special": g("byellow"),
        "SpecialChar": g("byellow"),
        "Tag": g("blue"),
        "Delimiter": g("fg_dim"),
        "SpecialComment": g("fg_dim", None, ["italic"]),
        "Debug": g("red"),
        "Underlined": g("cyan", None, ["underline"]),
        "Ignore": g("muted"),
        "Error": g("red", None, ["bold"]),
        "Todo": g("bg", "yellow", ["bold"]),
        "Added": g("green"),
        "Changed": g("blue"),
        "Removed": g("red"),
        "diffAdded": g("green"),
        "diffRemoved": g("red"),
        "diffChanged": g("blue"),
    }
    nvim = {
        "NormalFloat": g("fg", "surface2"),
        "FloatBorder": g("border", "surface2"),
        "FloatTitle": g("blue", "surface2", ["bold"]),
        "WinSeparator": g("border", "bg"),
        "CurSearch": g("bg", "byellow", ["bold"]),
        "WinBar": g("fg_dim", "bg", ["bold"]),
        "WinBarNC": g("muted", "bg"),
        "MsgArea": g("fg", "bg"),
        "DiagnosticError": g("red"),
        "DiagnosticWarn": g("yellow"),
        "DiagnosticInfo": g("blue"),
        "DiagnosticHint": g("cyan"),
        "DiagnosticOk": g("green"),
        "DiagnosticUnderlineError": g(None, None, ["undercurl"], "red"),
        "DiagnosticUnderlineWarn": g(None, None, ["undercurl"], "yellow"),
        "DiagnosticUnderlineInfo": g(None, None, ["undercurl"], "blue"),
        "DiagnosticUnderlineHint": g(None, None, ["undercurl"], "cyan"),
        "DiagnosticUnderlineOk": g(None, None, ["undercurl"], "green"),
        "DiagnosticVirtualTextError": g("red", "diff_del"),
        "DiagnosticVirtualTextWarn": g("yellow", "surface"),
        "DiagnosticVirtualTextInfo": g("blue", "surface"),
        "DiagnosticVirtualTextHint": g("cyan", "surface"),
        "DiagnosticUnnecessary": g("muted"),
        "DiagnosticDeprecated": g(None, None, ["strikethrough"]),
        "LspReferenceText": g(None, "overlay"),
        "LspReferenceRead": g(None, "overlay"),
        "LspReferenceWrite": g(None, "overlay", ["bold"]),
        "LspInlayHint": g("muted", "surface"),
        "LspSignatureActiveParameter": g(None, "selection", ["bold"]),
        "@variable": g("fg"),
        "@variable.builtin": g("red"),
        "@variable.parameter": g("fg"),
        "@variable.member": g("bblue"),
        "@property": g("bblue"),
        "@constant.builtin": g("yellow"),
        "@module": g("cyan"),
        "@string.escape": g("byellow"),
        "@string.regexp": g("byellow"),
        "@string.special.url": g("cyan", None, ["underline"]),
        "@function.builtin": g("blue"),
        "@function.macro": g("bviolet"),
        "@constructor": g("cyan"),
        "@keyword.import": g("bviolet"),
        "@keyword.operator": g("violet"),
        "@punctuation": g("fg_dim"),
        "@punctuation.special": g("bcyan"),
        "@tag": g("blue"),
        "@tag.attribute": g("yellow"),
        "@tag.delimiter": g("fg_dim"),
        "@markup.heading": g("blue", None, ["bold"]),
        "@markup.strong": g(None, None, ["bold"]),
        "@markup.italic": g(None, None, ["italic"]),
        "@markup.strikethrough": g(None, None, ["strikethrough"]),
        "@markup.link": g("blue"),
        "@markup.link.url": g("cyan", None, ["underline"]),
        "@markup.raw": g("green"),
        "@markup.quote": g("fg_dim", None, ["italic"]),
        "@markup.list": g("violet"),
        "@diff.plus": link("Added"),
        "@diff.minus": link("Removed"),
        "@diff.delta": link("Changed"),
    }
    return common, nvim


def cterm_index(p: Palette, hex_color: str | None) -> str:
    """Map a palette color to the closest of the 16 terminal colors.

    The monOS terminals use exactly the ANSI palette of monos.toml, so a
    16-color fallback (Linux console, no termguicolors) still looks right.
    """
    if hex_color is None:
        return "NONE"
    if hex_color.upper() in (p.ui["bg"].upper(), p.ui["fg"].upper()):
        return "NONE"  # the terminal's default background/foreground
    table = p.ansi16()
    for i, color in enumerate(table):
        if color.upper() == hex_color.upper():
            return str(i)

    def dist(a: str, b: str) -> int:
        return sum((ca - cb) ** 2 for ca, cb in zip(rgb(a), rgb(b)))

    return str(min(range(16), key=lambda i: dist(hex_color, table[i])))


def gen_vim_colors(p: Palette) -> None:
    common, nvim = editor_groups(p)
    x, u = p.ansi16(), p.ui

    def vim_line(name: str, spec: dict) -> str:
        if "link" in spec:
            return f"hi! link {name} {spec['link']}"
        style = ",".join(spec["style"]) or "NONE"
        cstyle = ",".join(s if s != "undercurl" else "underline" for s in spec["style"]) or "NONE"
        parts = [
            f"hi {name}",
            f"guifg={spec['fg'] or 'NONE'}",
            f"guibg={spec['bg'] or 'NONE'}",
            f"gui={style}",
            f"ctermfg={cterm_index(p, spec['fg'])}",
            f"ctermbg={cterm_index(p, spec['bg'])}",
            f"cterm={cstyle}",
        ]
        if spec.get("sp"):
            parts.append(f"guisp={spec['sp']}")
        return " ".join(parts)

    common_lines = "\n".join(vim_line(n, s) for n, s in common.items())
    nvim_lines = "\n".join("  " + vim_line(n, s) for n, s in nvim.items() if not n.startswith("@"))
    terminal = ", ".join(f"'{c}'" for c in x)
    colors = f"""{header('"')}" monOS colorscheme for Vim (and Neovim, which prefers colors/monos.lua).
" Uses 24-bit colors with 'termguicolors' or in gVim, and the 16 terminal
" colors otherwise (the monOS terminals use the same palette).

set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'monos'

let g:terminal_ansi_colors = [{terminal}]

{common_lines}
if has('nvim')
{nvim_lines}
endif
"""
    write(AIROOTFS / "usr" / "share" / "vim" / "vimfiles" / "colors" / "monos.vim", colors)

    plugin = f"""{header('"')}" monOS: use the monos colorscheme when the user configuration did not
" choose one. Any `colorscheme` command in ~/.vimrc runs before this file,
" sets g:colors_name and therefore wins. Remove this behavior with
"   let g:monos_no_default_colorscheme = 1
" in ~/.vimrc.
if has('nvim') || exists('g:monos_no_default_colorscheme') || exists('g:colors_name')
  finish
endif
if has('gui_running') || &termguicolors || &t_Co >= 16
  silent! colorscheme monos
endif
"""
    write(AIROOTFS / "usr" / "share" / "vim" / "vimfiles" / "plugin" / "monos.vim", plugin)

    # Neovim (Lua)
    def lua_spec(spec: dict, name: str) -> str:
        if "link" in spec:
            return f'  ["{name}"] = {{ link = "{spec["link"]}" }},'
        items = []
        if spec["fg"]:
            items.append(f'fg = "{spec["fg"]}"')
        if spec["bg"]:
            items.append(f'bg = "{spec["bg"]}"')
        if spec.get("sp"):
            items.append(f'sp = "{spec["sp"]}"')
        cfg = cterm_index(p, spec["fg"])
        cbg = cterm_index(p, spec["bg"])
        if cfg != "NONE":
            items.append(f"ctermfg = {cfg}")
        if cbg != "NONE":
            items.append(f"ctermbg = {cbg}")
        for s in spec["style"]:
            items.append(f"{s} = true")
        return f'  ["{name}"] = {{ {", ".join(items)} }},'

    groups = {**common, **nvim}
    lua_groups = "\n".join(lua_spec(s, n) for n, s in groups.items())
    terminal_lua = "\n".join(f'vim.g.terminal_color_{i} = "{c}"' for i, c in enumerate(x))
    lua = f"""{header('--')}-- monOS colorscheme for Neovim: `:colorscheme monos`.
-- 24-bit colors with 'termguicolors' (default in kitty/foot), otherwise the
-- 16 terminal colors (the monOS terminals use the same palette).

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "monos"

local groups = {{
{lua_groups}
}}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

{terminal_lua}
"""
    nvim_site = AIROOTFS / "usr" / "local" / "share" / "nvim" / "site"
    write(nvim_site / "colors" / "monos.lua", lua)

    nvim_plugin = f"""{header('--')}-- monOS: use the monos colorscheme when the user configuration did not choose
-- one. init.lua/init.vim run before plugin/ files, so any `colorscheme` there
-- (or in a plugin manager that loads it during init) wins. Disable with
--   vim.g.monos_no_default_colorscheme = true
-- in init.lua.
if vim.g.monos_no_default_colorscheme or vim.g.colors_name then
  return
end
pcall(vim.cmd.colorscheme, "monos")
"""
    write(nvim_site / "plugin" / "monos.lua", nvim_plugin)


# --------------------------------------------------------------------------
# KDE Plasma
# --------------------------------------------------------------------------
def kde_color_groups(p: Palette) -> str:
    u, x = p.ui, p.ansi
    fg_common = {
        "ForegroundNormal": u["fg"],
        "ForegroundInactive": u["fg-dim"],
        "ForegroundActive": x["blue"],
        "ForegroundLink": x["blue"],
        "ForegroundVisited": x["bright-magenta"],
        "ForegroundNegative": x["red"],
        "ForegroundNeutral": x["yellow"],
        "ForegroundPositive": x["green"],
        "DecorationFocus": u["accent"],
        "DecorationHover": x["blue"],
    }
    groups = {
        "Colors:Button": {"BackgroundNormal": u["overlay"], "BackgroundAlternate": u["selection"]},
        "Colors:Complementary": {"BackgroundNormal": u["bg"], "BackgroundAlternate": u["surface"]},
        "Colors:Header": {"BackgroundNormal": u["surface2"], "BackgroundAlternate": u["surface"]},
        "Colors:Header][Inactive": {"BackgroundNormal": u["surface"], "BackgroundAlternate": u["surface2"]},
        "Colors:Selection": {"BackgroundNormal": u["accent"], "BackgroundAlternate": u["selection"]},
        "Colors:Tooltip": {"BackgroundNormal": u["surface2"], "BackgroundAlternate": u["surface"]},
        "Colors:View": {"BackgroundNormal": u["surface"], "BackgroundAlternate": mix(u["surface"], u["surface2"], 0.5)},
        "Colors:Window": {"BackgroundNormal": u["surface2"], "BackgroundAlternate": u["overlay"]},
    }
    selection_fg = {
        "ForegroundNormal": u["accent-fg"],
        "ForegroundInactive": mix(u["accent-fg"], u["accent"], 0.3),
        "ForegroundActive": u["accent-fg"],
        "ForegroundLink": x["bright-yellow"],
        "ForegroundVisited": x["bright-magenta"],
        "ForegroundNegative": x["bright-red"],
        "ForegroundNeutral": x["bright-yellow"],
        "ForegroundPositive": x["bright-green"],
    }
    out = [
        "[ColorEffects:Disabled]",
        f"Color={kde_rgb(u['surface2'])}",
        "ColorAmount=0",
        "ColorEffect=0",
        "ContrastAmount=0.65",
        "ContrastEffect=1",
        "IntensityAmount=0.1",
        "IntensityEffect=2",
        "",
        "[ColorEffects:Inactive]",
        "ChangeSelectionColor=true",
        f"Color={kde_rgb(u['muted'])}",
        "ColorAmount=0.025",
        "ColorEffect=2",
        "ContrastAmount=0.1",
        "ContrastEffect=2",
        "Enable=false",
        "IntensityAmount=0",
        "IntensityEffect=0",
        "",
    ]
    for name, bgs in groups.items():
        values = dict(fg_common)
        if name == "Colors:Selection":
            values.update(selection_fg)
        values.update(bgs)
        out.append(f"[{name}]")
        out += [f"{k}={kde_rgb(v)}" for k, v in sorted(values.items())]
        out.append("")
    out += [
        "[WM]",
        f"activeBackground={kde_rgb(u['surface2'])}",
        f"activeBlend={kde_rgb(u['fg'])}",
        f"activeForeground={kde_rgb(u['fg'])}",
        f"inactiveBackground={kde_rgb(u['surface'])}",
        f"inactiveBlend={kde_rgb(u['fg-dim'])}",
        f"inactiveForeground={kde_rgb(u['fg-dim'])}",
    ]
    return "\n".join(out) + "\n"


def gen_kde(p: Palette) -> None:
    u = p.ui
    colors = f"""{header('#')}
[General]
ColorScheme={COLOR_SCHEME}
Name=monOS Dark
shadeSortColumn=true

[KDE]
contrast=4

{kde_color_groups(p)}"""
    write(AIROOTFS / "usr" / "share" / "color-schemes" / f"{COLOR_SCHEME}.colors", colors)

    # System-wide KDE defaults. Plasma also writes the Global Theme defaults
    # to ~/.config/kdedefaults at login (startplasma), which applies the
    # colors, icons, cursor, splash and window decoration for new users.
    # The color groups are repeated here so that KDE applications started
    # outside Plasma (e.g. Calamares as root) use the monOS colors too.
    kdeglobals = f"""{header('#', 'System-wide KDE defaults for monOS (users can override everything).')}
[General]
TerminalApplication=kitty
TerminalService=kitty.desktop
ColorScheme={COLOR_SCHEME}
fixed={FIXED_FONT}
font={UI_FONT}
menuFont={UI_FONT}
toolBarFont={UI_FONT}
smallestReadableFont={SMALL_FONT}

[WM]
activeFont={TITLE_FONT}

[KDE]
LookAndFeelPackage={LOOK_AND_FEEL_ID}
widgetStyle={WIDGET_STYLE}
AnimationDurationFactor={ANIMATION_DURATION_FACTOR}

[Icons]
Theme={ICON_THEME}

{kde_color_groups(p)}"""
    write(AIROOTFS / "etc" / "xdg" / "kdeglobals", kdeglobals)

    write(
        AIROOTFS / "etc" / "xdg" / "ksplashrc",
        f"{header('#')}[KSplash]\nEngine=KSplashQML\nTheme={LOOK_AND_FEEL_ID}\n",
    )
    lock_image = f"/usr/share/wallpapers/{WALLPAPER_DEFAULT}/"
    write(
        AIROOTFS / "etc" / "xdg" / "kscreenlockerrc",
        f"""{header('#')}[Greeter]
WallpaperPlugin=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image={lock_image}
PreviewImage={lock_image}
""",
    )

    lnf = AIROOTFS / "usr" / "share" / "plasma" / "look-and-feel" / LOOK_AND_FEEL_ID
    metadata = {
        "KPackageStructure": "Plasma/LookAndFeel",
        "KPlugin": {
            "Authors": [{"Name": "monOS Project"}],
            "Category": "",
            "Description": (
                "monOS dark desktop: brand colors, Klassy style and window decorations, "
                "Yamis monochrome icons, Bibata cursor and a floating dock-style panel"
            ),
            "Id": LOOK_AND_FEEL_ID,
            "License": "GPL-2.0-or-later",
            "Name": "monOS",
            "Version": "1.0",
            "Website": "https://github.com/FreidhYMorales/monOS",
        },
        "X-Plasma-APIVersion": "2",
    }
    write(lnf / "metadata.json", json.dumps(metadata, indent=4) + "\n")

    defaults = f"""{header('#')}[kdeglobals][KDE]
widgetStyle={WIDGET_STYLE}

[kdeglobals][General]
ColorScheme={COLOR_SCHEME}

[kdeglobals][Icons]
Theme={ICON_THEME}

[plasmarc][Theme]
name=default

[Wallpaper]
Image={WALLPAPER_DEFAULT}

[kcminputrc][Mouse]
cursorTheme={CURSOR_THEME}
cursorSize={CURSOR_SIZE}

[kwinrc][org.kde.kdecoration2]
library={DECORATION_LIBRARY}
theme={DECORATION_THEME}

[ksplashrc][KSplash]
Theme={LOOK_AND_FEEL_ID}
"""
    write(lnf / "contents" / "defaults", defaults)

    launchers = ", ".join(f'"{app}"' for app in PINNED_APPS)
    layout = f"""{header('//')}// monOS default desktop layout (Plasma 6 desktop scripting API).
// Used by plasmashell when a user has no panel configuration yet (first
// login), and by System Settings > Global Theme > monOS with
// "Desktop and window layout" checked.

// Wallpaper: monOS Orbit on every desktop.
var allDesktops = desktops();
for (var i = 0; i < allDesktops.length; i++) {{
    var desktop = allDesktops[i];
    desktop.wallpaperPlugin = "org.kde.image";
    desktop.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"];
    desktop.writeConfig("Image", "file:///usr/share/wallpapers/{WALLPAPER_DEFAULT}/");
}}

// One floating panel at the bottom.
var panel = new Panel;
panel.location = "bottom";
panel.floating = true;
// Translucent, so KWin's blur effect shows behind it.
panel.opacity = "translucent";
panel.height = 2 * Math.ceil(gridUnit * 2.5 / 2);

// Keep the panel at most as wide as a 21:9 screen, like Plasma's default.
var maximumAspectRatio = 21 / 9;
var geo = screenGeometry(panel.screen);
var maximumWidth = Math.ceil(geo.height * maximumAspectRatio);
if (geo.width > maximumWidth) {{
    panel.alignment = "center";
    panel.minimumLength = maximumWidth;
    panel.maximumLength = maximumWidth;
}}

var kickoff = panel.addWidget("org.kde.plasma.kickoff");
kickoff.currentConfigGroup = ["General"];
kickoff.writeConfig("icon", "{KICKOFF_ICON}");

var tasks = panel.addWidget("org.kde.plasma.icontasks");
tasks.currentConfigGroup = ["General"];
tasks.writeConfig("launchers", [{launchers}]);

panel.addWidget("org.kde.plasma.marginsseparator");
panel.addWidget("org.kde.plasma.systemtray");
panel.addWidget("org.kde.plasma.digitalclock");
panel.addWidget("org.kde.plasma.showdesktop");
"""
    write(lnf / "contents" / "layouts" / "org.kde.plasma.desktop-layout.js", layout)

    splash = f"""{header('//')}// monOS KSplash screen (Plasma 6): logo on the brand background with a
// thin indeterminate progress bar. `stage` goes from 1 to 6 while the
// session starts; ksplash closes the window when Plasma is ready.

import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {{
    id: root
    color: "{u['bg']}"

    property int stage

    onStageChanged: {{
        if (stage == 2) {{
            introAnimation.running = true;
        }}
    }}

    Item {{
        id: content
        anchors.fill: parent
        opacity: 0

        Image {{
            id: logo
            readonly property real size: Kirigami.Units.gridUnit * 10
            anchors.centerIn: parent
            asynchronous: true
            source: "images/monos.svg"
            sourceSize.width: size
            sourceSize.height: size
        }}

        // Track and moving segment of the progress indicator.
        Rectangle {{
            id: track
            width: Kirigami.Units.gridUnit * 8
            height: 3
            radius: height / 2
            color: "{u['overlay']}"
            clip: true
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: logo.bottom
            anchors.topMargin: Kirigami.Units.gridUnit * 2

            Rectangle {{
                id: segment
                width: track.width * 0.35
                height: track.height
                radius: height / 2
                color: "{u['accent']}"

                XAnimator on x {{
                    from: -segment.width
                    to: track.width
                    duration: 1400
                    loops: Animation.Infinite
                    easing.type: Easing.InOutQuad
                    // No animation when the user disabled animations.
                    running: Kirigami.Units.longDuration > 1
                }}
            }}
        }}

        // Progress of the session start (stages 1..6) under the indicator.
        Rectangle {{
            width: track.width * Math.min(root.stage, 6) / 6
            height: 1
            color: "{u['violet-text']}"
            opacity: 0.6
            anchors.left: track.left
            anchors.top: track.bottom
            anchors.topMargin: 4
            Behavior on width {{
                NumberAnimation {{ duration: Kirigami.Units.longDuration }}
            }}
        }}
    }}

    OpacityAnimator {{
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }}
}}
"""
    write(lnf / "contents" / "splash" / "Splash.qml", splash)


def desktop_id(index: int) -> str:
    """Stable virtual desktop id (KWin generates a random UUID when Id_N is missing)."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"https://monos/virtual-desktop/{index}"))


def gen_kwin() -> None:
    """System-wide KWin and input defaults (/etc/xdg is in KWin's config cascade)."""
    desktops = "\n".join(f"Id_{i}={desktop_id(i)}" for i in range(1, VIRTUAL_DESKTOPS + 1))
    kwinrc = f"""{header('#', 'System-wide KWin defaults for monOS (users can override everything).')}
[org.kde.kdecoration2]
library={DECORATION_LIBRARY}
theme={DECORATION_THEME}

[Plugins]
blurEnabled=true
# Dynamic tiling (Krohnkite) is installed but off; toggle it with
# {TILING_TOGGLE_SHORTCUT} (monos-tiling-toggle) or System Settings > Window
# Management > KWin Scripts.
krohnkiteEnabled=false

# Lighter than Plasma's default (15): fewer blur passes, cheaper in VMs.
[Effect-blur]
BlurStrength=8
NoiseStrength=2

[Desktops]
Number={VIRTUAL_DESKTOPS}
Rows=1
{desktops}

# Plasma 6.7 modes: Constant, DarkLight (follows the system sunset/sunrise schedule).
[NightColor]
Active=true
Mode=DarkLight
"""
    write(AIROOTFS / "etc" / "xdg" / "kwinrc", kwinrc)

    # KWin (Wayland), Plasma (XCURSOR_THEME for X11 apps) and kde-gtk-config
    # (GTK settings.ini/gsettings, applied by its kded module at login) read the
    # cursor from kcminputrc.
    kcminputrc = f"""{header('#')}[Mouse]
cursorTheme={CURSOR_THEME}
cursorSize={CURSOR_SIZE}
"""
    write(AIROOTFS / "etc" / "xdg" / "kcminputrc", kcminputrc)


def gen_klassy(p: Palette) -> None:
    """Klassy decoration + style defaults.

    Klassy opens "klassy/klassyrc" with KSharedConfig's default (cascading)
    mode, so /etc/xdg/klassy/klassyrc provides defaults and the user's
    ~/.config/klassy/klassyrc (written by Klassy Settings) overrides them.
    Accent colors come from the color scheme (Selection = ui.accent).
    """
    content = f"""{header('#', 'System-wide Klassy defaults for monOS (Klassy Settings writes user overrides).')}
[Windeco]
ButtonIconStyle=StyleMaterialDynamic
ButtonShape=ShapeSmallCircle
IconSize=IconMedium
# Title bar uses the application's window color (MonosDark Window = ui.surface2)
# with no separator line, so it blends into the window.
MatchTitleBarToApplicationColor=true
DrawTitleBarSeparator=false
DrawBackgroundGradient=false
# The title font weight comes from kdeglobals [WM] activeFont.
BoldTitle=false
WindowCornerRadius=8
RoundAllCornersWhenNoBorders=true
UseTitleBarColorForAllBorders=true
DrawBorderOnMaximizedWindows=false
ColorizeWindowOutlineWithButton=false
AnimationsEnabled=true
AnimationsSpeedRelativeSystem=0

[ButtonSizing]
ScaleBackgroundPercent=110
ButtonSpacingLeft=6
ButtonSpacingRight=8
ButtonCornerRadius=SameAsWindow

# Every button (close included) gets the monOS accent ({p.ui['accent']}) behind
# its icon on hover/press.
[ButtonColors]
LockButtonColorsActiveInactive=true
ButtonIconColorsActive=TitleBarText
ButtonIconColorsInactive=TitleBarText
ButtonBackgroundColorsActive=Accent
ButtonBackgroundColorsInactive=Accent
NegativeCloseBackgroundHoverPressActive=false
NegativeCloseBackgroundHoverPressInactive=false
CloseButtonIconColorActive=WhiteWhenHoverPress
CloseButtonIconColorInactive=WhiteWhenHoverPress
ButtonBackgroundOpacityActive=100
ButtonBackgroundOpacityInactive=100

[TitleBarSpacing]
TitleAlignment=AlignCenterFullWidth
TitleBarTopMargin=4
TitleBarBottomMargin=4
LockTitleBarTopBottomMargins=true
TitleBarLeftMargin=4
TitleBarRightMargin=4
LockTitleBarLeftRightMargins=true
TitleSidePadding=6

[TitleBarOpacity]
TitleBarOpacityActive=100
TitleBarOpacityInactive=100

# Active window: thin accent outline; inactive: neutral contrast outline.
[WindowOutlineStyle]
WindowOutlineThickness=1
LockWindowOutlineStyleActiveInactive=false
WindowOutlineStyleActive=WindowOutlineAccentWithContrast
WindowOutlineStyleInactive=WindowOutlineContrast

[ShadowStyle]
ShadowSizeActive=ShadowMedium
ShadowSizeInactive=ShadowSmall

# Application style: frames follow the window corner radius; slightly
# translucent menus (blurred by KWin).
[Style]
FrameCornerRadius=FCR_DerivedFromWindow
MenuOpacity=92
"""
    write(AIROOTFS / "etc" / "xdg" / "klassy" / "klassyrc", content)


def gen_shortcuts() -> None:
    """Global shortcuts for new users (skel) and the tiling toggle launcher.

    kglobalacceld opens kglobalshortcutsrc as KConfig::SimpleConfig, so
    /etc/xdg/kglobalshortcutsrc and ~/.config/kdedefaults are NOT read: the
    defaults have to be in the user's own file (copied from /etc/skel).
    Entry format: "<active keys, tab separated>,<default keys>,<friendly name>";
    service (.desktop) components use plain "_launch=<keys>".
    """
    lines = [header("#", "Default global shortcuts for new monOS users (System Settings > Shortcuts).")]
    lines.append("[kwin]")
    for i in range(1, VIRTUAL_DESKTOPS + 1):
        default = f"Meta+F{i}\\tCtrl+F{i}"
        lines.append(f"Switch to Desktop {i}=Meta+{i}\\t{default},{default},Switch to Desktop {i}")
    for i in range(1, VIRTUAL_DESKTOPS + 1):
        keys = "\\t".join(f"Meta+{sym}" for sym in SHIFTED_DIGITS[i])
        lines.append(f"Window to Desktop {i}={keys},none,Window to Desktop {i}")
    lines.append("KrohnkiteSetMaster=Meta+Shift+Return,Meta+Return,Krohnkite: Set master")
    lines.append("")
    lines.append("# Meta+1..4 switch virtual desktops instead of activating task manager entries.")
    lines.append("[plasmashell]")
    for i in range(1, VIRTUAL_DESKTOPS + 1):
        lines.append(
            f"activate task manager entry {i}=none,Meta+{i},Activate Task Manager Entry {i}"
        )
    lines.append("")
    for desktop_file, keys in APP_SHORTCUTS.items():
        lines.append(f"[services][{desktop_file}]")
        lines.append(f"_launch={keys}")
        lines.append("")
    write(SKEL_CFG / "kglobalshortcutsrc", "\n".join(lines))

    # Default shortcut for every user via X-KDE-Shortcuts (kglobalacceld
    # registers applications that declare it).
    toggle = f"""[Desktop Entry]
# {GEN_NOTE}
Type=Application
Name=Toggle Tiling (Krohnkite)
Comment=Turn KWin dynamic tiling on or off
Exec=/usr/local/bin/monos-tiling-toggle
Icon=dialog-tile-clones
Terminal=false
StartupNotify=false
Categories=Utility;
Keywords=tiling;krohnkite;kwin;windows;
X-KDE-Shortcuts={TILING_TOGGLE_SHORTCUT}
"""
    write(AIROOTFS / "usr" / "local" / "share" / "applications" / "monos-tiling-toggle.desktop", toggle)


def gen_dolphin() -> None:
    # dolphinrc is a cascading KConfig: /etc/xdg works as system default.
    dolphinrc = f"""{header('#')}[General]
EditableUrl=true
ShowFullPath=true
ShowFullPathInTitlebar=true
GlobalViewProps=true
"""
    write(AIROOTFS / "etc" / "xdg" / "dolphinrc", dolphinrc)
    # View properties (view mode, hidden files) are not in dolphinrc: with
    # GlobalViewProps they live in ~/.local/share/dolphin/view_properties/global/.directory
    # (Dolphin 26.08, ViewProperties::destinationDir), so new users get them from skel.
    # ViewMode: 0 icons, 1 details, 2 compact.
    view = f"""{header('#')}[Dolphin]
Version=4
ViewMode=1

[Settings]
HiddenFilesShown=true
"""
    write(SKEL / ".local" / "share" / "dolphin" / "view_properties" / "global" / ".directory", view)


# --------------------------------------------------------------------------
# VS Code (Code - OSS, Arch package "code")
# --------------------------------------------------------------------------
def gen_vscode(p: Palette) -> None:
    u, x = p.ui, p.ansi

    def a(color: str, alpha: int) -> str:
        return f"{color}{alpha:02X}"

    colors = {
        "foreground": u["fg"],
        "descriptionForeground": u["fg-dim"],
        "disabledForeground": u["muted"],
        "errorForeground": x["red"],
        "focusBorder": u["accent"],
        "contrastBorder": "#00000000",
        "selection.background": u["selection"],
        "widget.shadow": "#00000080",
        "icon.foreground": u["fg-dim"],
        "textLink.foreground": u["accent-text"],
        "textLink.activeForeground": x["bright-blue"],
        "textPreformat.foreground": x["green"],
        "textBlockQuote.background": u["surface"],
        "textBlockQuote.border": u["accent"],
        "textCodeBlock.background": u["surface"],
        "button.background": u["accent"],
        "button.foreground": u["accent-fg"],
        "button.hoverBackground": mix(u["accent"], u["accent-fg"], 0.12),
        "button.secondaryBackground": u["overlay"],
        "button.secondaryForeground": u["fg"],
        "button.secondaryHoverBackground": u["border"],
        "checkbox.background": u["surface2"],
        "checkbox.border": u["border"],
        "dropdown.background": u["surface2"],
        "dropdown.border": u["border"],
        "dropdown.foreground": u["fg"],
        "input.background": u["surface2"],
        "input.border": u["border"],
        "input.foreground": u["fg"],
        "input.placeholderForeground": u["muted"],
        "inputOption.activeBackground": a(u["accent"], 0x40),
        "inputOption.activeBorder": u["accent"],
        "inputValidation.errorBorder": x["red"],
        "inputValidation.warningBorder": x["yellow"],
        "inputValidation.infoBorder": x["blue"],
        "badge.background": u["accent"],
        "badge.foreground": u["accent-fg"],
        "progressBar.background": u["accent"],
        "scrollbar.shadow": "#00000060",
        "scrollbarSlider.background": a(u["border"], 0x99),
        "scrollbarSlider.hoverBackground": a(u["muted"], 0x80),
        "scrollbarSlider.activeBackground": a(u["accent"], 0x99),
        "titleBar.activeBackground": u["surface"],
        "titleBar.activeForeground": u["fg"],
        "titleBar.inactiveBackground": u["surface"],
        "titleBar.inactiveForeground": u["muted"],
        "titleBar.border": u["border"],
        "menubar.selectionBackground": u["overlay"],
        "menu.background": u["surface2"],
        "menu.foreground": u["fg"],
        "menu.selectionBackground": u["selection"],
        "menu.selectionForeground": u["fg"],
        "menu.separatorBackground": u["border"],
        "menu.border": u["border"],
        "activityBar.background": u["surface"],
        "activityBar.foreground": u["fg"],
        "activityBar.inactiveForeground": u["muted"],
        "activityBar.border": u["border"],
        "activityBar.activeBorder": u["accent"],
        "activityBarBadge.background": u["accent"],
        "activityBarBadge.foreground": u["accent-fg"],
        "sideBar.background": u["surface"],
        "sideBar.foreground": u["fg-dim"],
        "sideBar.border": u["border"],
        "sideBarTitle.foreground": u["fg"],
        "sideBarSectionHeader.background": u["surface"],
        "sideBarSectionHeader.foreground": u["fg"],
        "sideBarSectionHeader.border": u["border"],
        "list.activeSelectionBackground": u["selection"],
        "list.activeSelectionForeground": u["fg"],
        "list.inactiveSelectionBackground": u["surface2"],
        "list.inactiveSelectionForeground": u["fg"],
        "list.hoverBackground": u["surface2"],
        "list.hoverForeground": u["fg"],
        "list.focusOutline": u["accent"],
        "list.highlightForeground": u["accent-text"],
        "list.errorForeground": x["red"],
        "list.warningForeground": x["yellow"],
        "tree.indentGuidesStroke": u["border"],
        "editorGroup.border": u["border"],
        "editorGroupHeader.tabsBackground": u["surface"],
        "editorGroupHeader.tabsBorder": u["border"],
        "tab.activeBackground": u["bg"],
        "tab.activeForeground": u["fg"],
        "tab.activeBorderTop": u["accent"],
        "tab.unfocusedActiveBorderTop": u["border"],
        "tab.inactiveBackground": u["surface"],
        "tab.inactiveForeground": u["fg-dim"],
        "tab.hoverBackground": u["surface2"],
        "tab.border": u["border"],
        "breadcrumb.foreground": u["fg-dim"],
        "breadcrumb.focusForeground": u["fg"],
        "breadcrumb.activeSelectionForeground": u["accent-text"],
        "editor.background": u["bg"],
        "editor.foreground": u["fg"],
        "editorCursor.foreground": u["cursor"],
        "editorLineNumber.foreground": u["muted"],
        "editorLineNumber.activeForeground": u["fg"],
        "editor.lineHighlightBackground": u["surface"],
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": u["selection"],
        "editor.inactiveSelectionBackground": a(u["selection"], 0x99),
        "editor.selectionHighlightBackground": a(u["selection"], 0x80),
        "editor.wordHighlightBackground": a(u["overlay"], 0xCC),
        "editor.wordHighlightStrongBackground": a(u["selection"], 0xCC),
        "editor.findMatchBackground": a(x["yellow"], 0x55),
        "editor.findMatchHighlightBackground": a(x["yellow"], 0x2A),
        "editor.findRangeHighlightBackground": a(u["surface2"], 0x99),
        "editor.rangeHighlightBackground": a(u["surface2"], 0x99),
        "editorLink.activeForeground": x["cyan"],
        "editorWhitespace.foreground": u["border"],
        "editorIndentGuide.background1": u["border"],
        "editorIndentGuide.activeBackground1": u["muted"],
        "editorRuler.foreground": u["border"],
        "editorBracketMatch.background": a(u["overlay"], 0xCC),
        "editorBracketMatch.border": u["muted"],
        "editorBracketHighlight.foreground1": x["blue"],
        "editorBracketHighlight.foreground2": u["violet-text"],
        "editorBracketHighlight.foreground3": x["cyan"],
        "editorBracketHighlight.foreground4": x["yellow"],
        "editorBracketHighlight.foreground5": x["green"],
        "editorBracketHighlight.foreground6": x["bright-magenta"],
        "editorBracketHighlight.unexpectedBracket.foreground": x["red"],
        "editorCodeLens.foreground": u["muted"],
        "editorInlayHint.foreground": u["muted"],
        "editorInlayHint.background": u["surface"],
        "editorError.foreground": x["red"],
        "editorWarning.foreground": x["yellow"],
        "editorInfo.foreground": x["blue"],
        "editorHint.foreground": x["cyan"],
        "editorGutter.background": u["bg"],
        "editorGutter.addedBackground": x["green"],
        "editorGutter.modifiedBackground": x["blue"],
        "editorGutter.deletedBackground": x["red"],
        "editorOverviewRuler.border": u["border"],
        "editorOverviewRuler.errorForeground": x["red"],
        "editorOverviewRuler.warningForeground": x["yellow"],
        "editorOverviewRuler.infoForeground": x["blue"],
        "editorWidget.background": u["surface2"],
        "editorWidget.foreground": u["fg"],
        "editorWidget.border": u["border"],
        "editorSuggestWidget.background": u["surface2"],
        "editorSuggestWidget.border": u["border"],
        "editorSuggestWidget.foreground": u["fg"],
        "editorSuggestWidget.selectedBackground": u["selection"],
        "editorSuggestWidget.highlightForeground": u["accent-text"],
        "editorHoverWidget.background": u["surface2"],
        "editorHoverWidget.border": u["border"],
        "peekView.border": u["accent"],
        "peekViewEditor.background": u["surface"],
        "peekViewResult.background": u["surface2"],
        "peekViewTitle.background": u["surface2"],
        "peekViewEditor.matchHighlightBackground": a(x["yellow"], 0x40),
        "peekViewResult.matchHighlightBackground": a(x["yellow"], 0x40),
        "diffEditor.insertedTextBackground": a(x["green"], 0x26),
        "diffEditor.removedTextBackground": a(x["red"], 0x26),
        "diffEditor.insertedLineBackground": a(x["green"], 0x14),
        "diffEditor.removedLineBackground": a(x["red"], 0x14),
        "merge.currentHeaderBackground": a(x["green"], 0x55),
        "merge.incomingHeaderBackground": a(x["blue"], 0x55),
        "panel.background": u["surface"],
        "panel.border": u["border"],
        "panelTitle.activeBorder": u["accent"],
        "panelTitle.activeForeground": u["fg"],
        "panelTitle.inactiveForeground": u["fg-dim"],
        "statusBar.background": u["surface"],
        "statusBar.foreground": u["fg-dim"],
        "statusBar.border": u["border"],
        "statusBar.noFolderBackground": u["surface"],
        "statusBar.debuggingBackground": u["violet"],
        "statusBar.debuggingForeground": u["accent-fg"],
        "statusBarItem.hoverBackground": u["overlay"],
        "statusBarItem.remoteBackground": u["accent"],
        "statusBarItem.remoteForeground": u["accent-fg"],
        "quickInput.background": u["surface2"],
        "quickInput.foreground": u["fg"],
        "quickInputList.focusBackground": u["selection"],
        "pickerGroup.foreground": u["accent-text"],
        "pickerGroup.border": u["border"],
        "keybindingLabel.background": u["overlay"],
        "keybindingLabel.foreground": u["fg"],
        "keybindingLabel.border": u["border"],
        "keybindingLabel.bottomBorder": u["border"],
        "notifications.background": u["surface2"],
        "notifications.foreground": u["fg"],
        "notifications.border": u["border"],
        "notificationCenterHeader.background": u["overlay"],
        "notificationsErrorIcon.foreground": x["red"],
        "notificationsWarningIcon.foreground": x["yellow"],
        "notificationsInfoIcon.foreground": x["blue"],
        "gitDecoration.addedResourceForeground": x["green"],
        "gitDecoration.modifiedResourceForeground": x["yellow"],
        "gitDecoration.deletedResourceForeground": x["red"],
        "gitDecoration.untrackedResourceForeground": x["bright-green"],
        "gitDecoration.ignoredResourceForeground": u["muted"],
        "gitDecoration.conflictingResourceForeground": x["bright-magenta"],
        "terminal.background": u["bg"],
        "terminal.foreground": u["fg"],
        "terminal.selectionBackground": u["selection"],
        "terminalCursor.foreground": u["cursor"],
        "terminal.border": u["border"],
    }
    for i, name in enumerate(ANSI_NAMES):
        cap = name.capitalize()
        colors[f"terminal.ansi{cap}"] = x[name]
        colors[f"terminal.ansiBright{cap}"] = x[f"bright-{name}"]

    def rule(name: str, scope: list[str], fg: str | None = None, style: str | None = None) -> dict:
        settings: dict[str, str] = {}
        if fg:
            settings["foreground"] = fg
        if style is not None:
            settings["fontStyle"] = style
        return {"name": name, "scope": scope, "settings": settings}

    token_colors = [
        rule("Comment", ["comment", "punctuation.definition.comment"], u["muted"], "italic"),
        rule("String", ["string", "string.quoted", "string.template"], x["green"]),
        rule("Regex / escape", ["string.regexp", "constant.character.escape", "constant.other.placeholder"], x["bright-yellow"]),
        rule("Number / constant", ["constant.numeric", "constant.language", "constant.other", "support.constant", "variable.other.constant", "variable.other.enummember"], x["yellow"]),
        rule("Keyword", ["keyword", "keyword.control", "storage", "storage.type", "storage.modifier"], u["violet-text"]),
        rule("Import / preprocessor", ["keyword.control.import", "keyword.control.from", "keyword.control.export", "meta.preprocessor", "keyword.control.directive", "entity.name.function.macro", "entity.name.function.preprocessor"], x["bright-magenta"]),
        rule("Operator", ["keyword.operator", "punctuation.accessor"], x["bright-cyan"]),
        rule("Function", ["entity.name.function", "support.function", "meta.function-call.generic", "variable.function"], x["blue"]),
        rule("Type", ["entity.name.type", "entity.name.class", "entity.name.struct", "entity.name.enum", "entity.name.interface", "support.type", "support.class", "entity.other.inherited-class", "storage.type.primitive"], x["cyan"]),
        rule("Namespace", ["entity.name.namespace", "entity.name.module", "support.module"], x["cyan"]),
        rule("Variable", ["variable", "variable.other.readwrite", "variable.parameter", "meta.definition.variable"], u["fg"]),
        rule("Language variable", ["variable.language", "variable.language.this", "variable.language.self", "support.variable.builtin"], x["red"]),
        rule("Property", ["variable.other.property", "variable.other.member", "support.variable.property", "meta.object-literal.key", "entity.name.field"], x["bright-blue"]),
        rule("Tag", ["entity.name.tag", "punctuation.definition.tag"], x["blue"]),
        rule("Attribute", ["entity.other.attribute-name", "meta.attribute", "meta.decorator", "entity.name.function.decorator"], x["yellow"]),
        rule("Punctuation", ["punctuation", "meta.brace", "punctuation.separator", "punctuation.terminator"], u["fg-dim"]),
        rule("Heading", ["markup.heading", "entity.name.section"], x["blue"], "bold"),
        rule("Bold", ["markup.bold"], None, "bold"),
        rule("Italic", ["markup.italic"], None, "italic"),
        rule("Strikethrough", ["markup.strikethrough"], None, "strikethrough"),
        rule("Inline code", ["markup.inline.raw", "markup.fenced_code", "markup.raw"], x["green"]),
        rule("Link", ["markup.underline.link", "string.other.link"], x["cyan"]),
        rule("Quote", ["markup.quote"], u["fg-dim"], "italic"),
        rule("List", ["markup.list", "punctuation.definition.list"], u["violet-text"]),
        rule("Diff inserted", ["markup.inserted", "meta.diff.header.to-file"], x["green"]),
        rule("Diff deleted", ["markup.deleted", "meta.diff.header.from-file"], x["red"]),
        rule("Diff changed", ["markup.changed"], x["yellow"]),
        rule("Invalid", ["invalid", "invalid.illegal"], x["red"]),
        rule("Deprecated", ["invalid.deprecated"], u["muted"], "strikethrough"),
    ]
    semantic = {
        "namespace": x["cyan"],
        "type": x["cyan"],
        "class": x["cyan"],
        "enum": x["cyan"],
        "interface": x["cyan"],
        "struct": x["cyan"],
        "typeParameter": x["cyan"],
        "function": x["blue"],
        "method": x["blue"],
        "macro": x["bright-magenta"],
        "property": x["bright-blue"],
        "enumMember": x["yellow"],
        "variable": u["fg"],
        "parameter": u["fg"],
        "variable.readonly": x["yellow"],
        "variable.defaultLibrary": x["red"],
        "keyword": u["violet-text"],
        "decorator": x["yellow"],
        "*.deprecated": {"strikethrough": True},
    }
    theme = {
        "$schema": "vscode://schemas/color-theme",
        "name": VSCODE_THEME_NAME,
        "type": "dark",
        "semanticHighlighting": True,
        "colors": colors,
        "tokenColors": token_colors,
        "semanticTokenColors": semantic,
    }
    ext = AIROOTFS / "usr" / "lib" / "code" / "extensions" / VSCODE_EXTENSION
    package = {
        "name": VSCODE_EXTENSION,
        "displayName": "monOS Theme",
        "description": f"monOS dark color theme. {GEN_NOTE} (source: branding/palette/monos.toml).",
        "version": "1.0.0",
        "publisher": "monos",
        "license": "GPL-2.0-or-later",
        "engines": {"vscode": "*"},
        "categories": ["Themes"],
        "contributes": {
            "themes": [
                {
                    "id": VSCODE_THEME_NAME,
                    "label": VSCODE_THEME_NAME,
                    "uiTheme": "vs-dark",
                    "path": "./themes/monos-color-theme.json",
                }
            ]
        },
    }
    write(ext / "package.json", json.dumps(package, indent=2, ensure_ascii=False) + "\n")
    write(ext / "themes" / "monos-color-theme.json", json.dumps(theme, indent=2, ensure_ascii=False) + "\n")

    settings = {
        "workbench.colorTheme": VSCODE_THEME_NAME,
        "workbench.iconTheme": "vs-seti",
        "editor.fontFamily": "'JetBrainsMono Nerd Font', monospace",
        "editor.fontLigatures": True,
        "editor.fontSize": 14,
        "terminal.integrated.fontFamily": "'JetBrainsMono Nerd Font'",
        "window.titleBarStyle": "custom",
        "telemetry.telemetryLevel": "off",
        "telemetry.feedback.enabled": False,
        "workbench.enableExperiments": False,
        "workbench.settings.enableNaturalLanguageSearch": False,
    }
    note = (
        "Default VS Code (Code - OSS) settings for new monOS users. The \"monOS\" theme\n"
        f"is a built-in extension: /usr/lib/code/extensions/{VSCODE_EXTENSION}."
    )
    write(
        SKEL_CFG / "Code - OSS" / "User" / "settings.json",
        header("//", note) + json.dumps(settings, indent=2, ensure_ascii=False) + "\n",
    )


# --------------------------------------------------------------------------
# SDDM, Plymouth, GRUB, Syslinux, Calamares
# --------------------------------------------------------------------------
def gen_sddm(p: Palette) -> None:
    content = f"""{header('#', 'Overrides theme.conf of the Breeze SDDM theme (owned by plasma-desktop).')}[General]
type=image
color={p.ui['bg']}
background=/usr/share/wallpapers/{WALLPAPER_DEFAULT}/contents/images/3840x2160.jpg
showlogo=shown
logo=/usr/share/monos/logo/monos-wordmark.svg
"""
    write(AIROOTFS / "usr" / "share" / "sddm" / "themes" / "breeze" / "theme.conf.user", content)

    conf = f"""{header('#', 'SDDM greeter theme and cursor, for the live session and the installed system.')}# Breeze with the monOS Orbit background and logo (see
# /usr/share/sddm/themes/breeze/theme.conf.user).
[Theme]
Current=breeze
CursorTheme={CURSOR_THEME}
CursorSize={CURSOR_SIZE}
"""
    write(AIROOTFS / "etc" / "sddm.conf.d" / "10-monos-theme.conf", conf)


def hex0x(c: str) -> str:
    return "0x" + bare(c)


def gen_plymouth(p: Palette) -> None:
    u = p.ui
    content = f"""{header('#', 'Images: branding/tools/install-branding.sh')}[Plymouth Theme]
Name=monOS
Description=monOS logo on the brand background with a spinner.
ModuleName=two-step

[two-step]
Font=Adwaita Sans 12
TitleFont=Adwaita Sans Light 24
MonospaceFont=Adwaita Mono 12
ImageDir=/usr/share/plymouth/themes/monos
DialogHorizontalAlignment=.5
DialogVerticalAlignment=.75
TitleHorizontalAlignment=.5
TitleVerticalAlignment=.382
HorizontalAlignment=.5
VerticalAlignment=.75
WatermarkHorizontalAlignment=.5
WatermarkVerticalAlignment=.45
Transition=none
TransitionDuration=0.0
BackgroundStartColor={hex0x(u['bg'])}
BackgroundEndColor={hex0x(u['bg'])}
ProgressBarBackgroundColor={hex0x(u['overlay'])}
ProgressBarForegroundColor={hex0x(u['accent'])}
MessageBelowAnimation=true

[boot-up]
UseEndAnimation=false

[shutdown]
UseEndAnimation=false

[reboot]
UseEndAnimation=false

[updates]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Installing updates...
SubTitle=Do not turn off your computer

[system-upgrade]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Upgrading system...
SubTitle=Do not turn off your computer

[firmware-upgrade]
SuppressMessages=true
ProgressBarShowPercentComplete=true
UseProgressBar=true
Title=Upgrading firmware...
SubTitle=Do not turn off your computer
"""
    write(AIROOTFS / "usr" / "share" / "plymouth" / "themes" / "monos" / "monos.plymouth", content)


def gen_grub(p: Palette, fonts: dict[str, str]) -> None:
    u, x = p.ui, p.ansi
    note = (
        "Images and fonts: branding/tools/install-branding.sh.\n"
        "Installed system: copied to /boot/grub/themes/monos by monos-target-cleanup.sh."
    )
    content = f"""{header('#', note)}
title-text: ""
desktop-image: "background.jpg"
desktop-image-scale-method: "stretch"
desktop-color: "{u['bg']}"
terminal-font: "{fonts['mono']}"
terminal-box: "terminal_box_*.png"
terminal-left: "10%"
terminal-top: "10%"
terminal-width: "80%"
terminal-height: "80%"
terminal-border: "0"

+ boot_menu {{
    left = 20%
    top = 40%
    width = 60%
    height = 40%
    item_font = "{fonts['regular']}"
    selected_item_font = "{fonts['bold']}"
    item_color = "{x['white']}"
    selected_item_color = "{u['accent-fg']}"
    item_height = 36
    item_padding = 14
    item_spacing = 6
    icon_width = 0
    icon_height = 0
    item_icon_space = 0
    selected_item_pixmap_style = "select_*.png"
    scrollbar = true
    scrollbar_width = 4
    scrollbar_thumb = "scrollbar_thumb_*.png"
}}

+ label {{
    id = "__timeout__"
    left = 20%
    top = 82%
    width = 60%
    align = "center"
    font = "{fonts['regular']}"
    color = "{u['fg-dim']}"
    text = "Booting the selected entry in %d s"
}}

+ label {{
    left = 20%
    top = 88%
    width = 60%
    align = "center"
    font = "{fonts['small']}"
    color = "{u['muted']}"
    text = "Enter: boot    E: edit entry    C: command line"
}}
"""
    write(AIROOTFS / "usr" / "share" / "grub" / "themes" / "monos" / "theme.txt", content)


def argb(alpha: int, c: str) -> str:
    return f"#{alpha:02x}{bare(c)}"


def gen_syslinux(p: Palette) -> None:
    u, x = p.ui, p.ansi
    # vesamenu: "MENU COLOR <item> <ansi> <fg #AARRGGBB> <bg #AARRGGBB> <shadow>"
    block = f"""MENU COLOR screen       37;40   {argb(0x00, u['bg'])} {argb(0x00, u['bg'])} none
MENU COLOR border       30;44   {argb(0x00, u['bg'])} {argb(0x00, u['bg'])} none
MENU COLOR title        1;36;44 {argb(0xff, x['blue'])} {argb(0x00, u['bg'])} none
MENU COLOR sel          7;37;40 {argb(0xff, u['accent-fg'])} {argb(0xff, u['accent'])} none
MENU COLOR hotsel       1;7;37;40 {argb(0xff, u['accent-fg'])} {argb(0xff, u['accent'])} none
MENU COLOR unsel        37;44   {argb(0xff, x['white'])} {argb(0x00, u['bg'])} none
MENU COLOR hotkey       1;37;44 {argb(0xff, x['bright-blue'])} {argb(0x00, u['bg'])} none
MENU COLOR help         37;40   {argb(0xff, u['fg-dim'])} {argb(0x00, u['bg'])} none
MENU COLOR timeout_msg  37;40   {argb(0xff, u['muted'])} {argb(0x00, u['bg'])} none
MENU COLOR timeout      1;37;40 {argb(0xff, x['bright-blue'])} {argb(0x00, u['bg'])} none
MENU COLOR msg07        37;40   {argb(0xff, u['fg'])} {argb(0x00, u['bg'])} none
MENU COLOR tabmsg       31;40   {argb(0xff, u['muted'])} {argb(0x00, u['bg'])} none
MENU COLOR cmdmark      1;36;40 {argb(0xff, x['blue'])} {argb(0x00, u['bg'])} none
MENU COLOR cmdline      37;40   {argb(0xff, u['fg'])} {argb(0x00, u['bg'])} none"""
    path = PROFILE / "syslinux" / "archiso_head.cfg"
    text = path.read_text(encoding="utf-8")
    # Drop the original MENU COLOR lines once; later runs replace the block.
    if BEGIN_MARK not in text:
        text = re.sub(r"^MENU COLOR .*\n", "", text, flags=re.M)
        text = text.replace("MENU CLEAR", f"# {BEGIN_MARK}\n# {END_MARK}\n\nMENU CLEAR", 1)
    text = replace_block(text, block)
    write(path, text)


def gen_calamares(p: Palette) -> None:
    u = p.ui
    branding = AIROOTFS / "etc" / "calamares" / "branding" / "monos"
    desc_path = branding / "branding.desc"
    desc = desc_path.read_text(encoding="utf-8")
    style = {
        "SidebarBackground": u["bg"],
        "SidebarText": u["fg"],
        "SidebarTextCurrent": u["accent-fg"],
        "SidebarBackgroundCurrent": u["accent"],
    }
    for key, value in style.items():
        desc, n = re.subn(rf'^(\s*{key}:\s*)"[^"]*"', rf'\g<1>"{value}"', desc, flags=re.M)
        if n != 1:
            raise SystemExit(f"error: {desc_path}: style key {key} not found exactly once")
    desc = re.sub(
        r"^# Colors match the logo:.*$",
        f"# Colors come from branding/palette/monos.toml (gen-themes.py rewrites the style keys).",
        desc,
        flags=re.M,
    )
    write(desc_path, desc)

    qml_path = branding / "show.qml"
    qml = qml_path.read_text(encoding="utf-8")
    props = {
        "bgColor": u["bg"],
        "accentColor": u["accent-text"],
        "fgColor": u["fg"],
    }
    for key, value in props.items():
        qml, n = re.subn(
            rf'(readonly property color {key}: )"[^"]*"', rf'\g<1>"{value}"', qml
        )
        if n != 1:
            raise SystemExit(f"error: {qml_path}: property {key} not found exactly once")
    write(qml_path, qml)


def gen_os_release(p: Palette) -> None:
    """ANSI_COLOR (used by systemd and fastfetch for the distro name)."""
    path = AIROOTFS / "etc" / "os-release"
    r, g, b = rgb(p.ui["accent-text"])
    text, n = re.subn(r'^ANSI_COLOR=.*$', f'ANSI_COLOR="38;2;{r};{g};{b}"', path.read_text(encoding="utf-8"), flags=re.M)
    if n != 1:
        raise SystemExit(f"error: {path}: ANSI_COLOR not found exactly once")
    write(path, text)


# --------------------------------------------------------------------------
def read_grub_font_names() -> dict[str, str]:
    """Names of the PF2 fonts produced by install-branding.sh (NAME section)."""
    theme_dir = AIROOTFS / "usr" / "share" / "grub" / "themes" / "monos"
    wanted = {
        "regular": "noto-sans-regular-18.pf2",
        "bold": "noto-sans-bold-18.pf2",
        "small": "noto-sans-regular-14.pf2",
        "mono": "noto-sans-mono-regular-16.pf2",
    }
    # GRUB always has "Unifont Regular 16" when it only has unicode.pf2.
    names = {k: "Unifont Regular 16" for k in wanted}
    for key, filename in wanted.items():
        path = theme_dir / filename
        if not path.exists():
            continue
        data = path.read_bytes()
        idx = data.find(b"NAME")
        if idx < 0:
            continue
        length = int.from_bytes(data[idx + 4 : idx + 8], "big")
        names[key] = data[idx + 8 : idx + 8 + length].rstrip(b"\0").decode()
    return names


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only print the contrast report")
    args = parser.parse_args()

    with PALETTE_FILE.open("rb") as fh:
        palette = Palette(tomllib.load(fh))

    rows, ok = contrast_report(palette)
    print(":: Contrast ratios (WCAG 2.x)")
    print("\n".join(rows))
    if not ok:
        print("error: the palette does not meet its contrast targets", file=sys.stderr)
        return 1
    if args.check:
        return 0

    gen_kitty(palette)
    gen_foot(palette)
    gen_btop(palette)
    gen_yazi(palette)
    gen_bat()
    gen_lazygit(palette)
    gen_zellij(palette)
    gen_starship(palette)
    gen_zshrc(palette)
    gen_helix(palette)
    gen_fastfetch(palette)
    gen_vim_colors(palette)
    gen_kde(palette)
    gen_kwin()
    gen_klassy(palette)
    gen_shortcuts()
    gen_dolphin()
    gen_vscode(palette)
    gen_sddm(palette)
    gen_plymouth(palette)
    gen_grub(palette, read_grub_font_names())
    gen_syslinux(palette)
    gen_calamares(palette)
    gen_os_release(palette)
    write(AIROOTFS / "usr" / "share" / "monos" / "palette.toml", PALETTE_FILE.read_text(encoding="utf-8"))

    print(f":: {len(WRITTEN)} files rendered, {len(CHANGED)} changed")
    for path in CHANGED:
        print(f"   {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
