# monOS: GRUB for both UEFI (x86_64-efi, ESP at /boot/efi) and BIOS (i386-pc).
---
efiBootLoader: "grub"
kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"
loaderEntries:
    - "timeout 5"
    - "console-mode keep"
kernelParams: [ "quiet" ]
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "monOS"
installEFIFallback: true
installHybridGRUB: false
