# monOS: keyboard layout.
---
xOrgConfFileName: "/etc/X11/xorg.conf.d/00-keyboard.conf"
convertedKeymapPath: "/lib/kbd/keymaps/xkb"
# Debian-only file, not used on Arch.
writeEtcDefaultKeyboard: false
configure:
    kwin: false
    gnome: false
