-- Generated by branding/tools/gen-themes.py — do not edit
-- Source: branding/palette/monos.toml
-- monOS: use the monos colorscheme when the user configuration did not choose
-- one. init.lua/init.vim run before plugin/ files, so any `colorscheme` there
-- (or in a plugin manager that loads it during init) wins. Disable with
--   vim.g.monos_no_default_colorscheme = true
-- in init.lua.
if vim.g.monos_no_default_colorscheme or vim.g.colors_name then
  return
end
pcall(vim.cmd.colorscheme, "monos")
