" Generated by branding/tools/gen-themes.py — do not edit
" Source: branding/palette/monos.toml
" monOS: use the monos colorscheme when the user configuration did not
" choose one. Any `colorscheme` command in ~/.vimrc runs before this file,
" sets g:colors_name and therefore wins. Remove this behavior with
"   let g:monos_no_default_colorscheme = 1
" in ~/.vimrc.
if has('nvim') || exists('g:monos_no_default_colorscheme') || exists('g:colors_name')
  finish
endif
if has('gui_running') || &termguicolors || &t_Co >= 16
  silent! colorscheme monos
endif
