-- Generated by branding/tools/gen-themes.py — do not edit
-- Source: branding/palette/monos.toml
-- monOS yazi plugin setup. Every plugin is vendored in ./plugins (pinned
-- versions and licenses: plugins/monos-plugins.txt); nothing is downloaded.
-- Plugins that only run from a key or as previewers (bypass, clipboard,
-- lazygit, mediainfo, mount, ouch, piper) need no setup here.

-- Full border around the three panes.
require("full-border"):setup({ type = ui.Border.PLAIN })

-- Header line (tabs, clock) and status line (mode, size, name, position,
-- permissions) in the monOS colors.
require("yatline"):setup({
	section_separator = { open = "\u{e0b6}", close = "\u{e0b4}" },
	part_separator = { open = "\u{e0b7}", close = "\u{e0b5}" },
	inverse_separator = { open = "\u{e0d6}", close = "\u{e0d7}" },
	padding = { inner = 1, outer = 1 },

	style_a = {
		fg = "#FCFCFC",
		bg_mode = { normal = "#0C6BFA", select = "#7C3AED", un_set = "#F2555A" },
	},
	style_b = { bg = "#232833", fg = "#E6E9EF" },
	style_c = { bg = "#1A1E27", fg = "#A9B1C1" },

	permissions_t_fg = "#3FD68A",
	permissions_r_fg = "#F5C451",
	permissions_w_fg = "#F2555A",
	permissions_x_fg = "#22C3E6",
	permissions_s_fg = "#7D8699",

	tab_width = 20,

	selected = { icon = "\u{f0eed}", fg = "#F5C451" },
	copied = { icon = "\u{f4bb}", fg = "#3FD68A" },
	cut = { icon = "\u{f0c4}", fg = "#F2555A" },
	files = { icon = "\u{f15b}", fg = "#3D8BFF" },
	filtereds = { icon = "\u{f0b0}", fg = "#9B6BFF" },

	total = { icon = "\u{f0b8d}", fg = "#F5C451" },
	success = { icon = "\u{f00c}", fg = "#3FD68A" },
	failed = { icon = "\u{f00d}", fg = "#F2555A" },

	show_background = false,
	display_header_line = true,
	display_status_line = true,
	component_positions = { "header", "tab", "status" },

	header_line = {
		left = {
			section_a = { { type = "line", custom = false, name = "tabs", params = { "left" } } },
			section_b = {},
			section_c = {},
		},
		right = {
			section_a = { { type = "string", custom = false, name = "date", params = { "%H:%M" } } },
			section_b = {},
			section_c = {},
		},
	},

	status_line = {
		left = {
			section_a = { { type = "string", custom = false, name = "tab_mode" } },
			section_b = { { type = "string", custom = false, name = "hovered_size" } },
			section_c = {
				{ type = "string", custom = false, name = "hovered_name" },
				{ type = "coloreds", custom = false, name = "count" },
			},
		},
		right = {
			section_a = { { type = "string", custom = false, name = "cursor_position" } },
			section_b = { { type = "string", custom = false, name = "cursor_percentage" } },
			section_c = {
				-- params = false: the icon variant calls the deprecated File:icon().
				{ type = "string", custom = false, name = "hovered_file_extension", params = { false } },
				{ type = "coloreds", custom = false, name = "permissions" },
			},
		},
	},
})

-- Vim-style counts: 3j, 5k, 2gg (1-9 start a motion). Relative line numbers.
require("relative-motions"):setup({ show_numbers = "relative_absolute", show_motion = true })

-- fg (f g / f G / f f): search file contents or names with ripgrep + fzf and
-- jump to the result in yazi.
require("fg"):setup({ default_action = "jump" })

-- what-size (Ctrl-S): size of the selection or of the current directory.
require("what-size"):setup({})

if ya.uid then
	-- gvfs (M m / M u / g m ...): mount phones (MTP), SMB/SFTP shares, ... through
	-- GVFS. Needs a D-Bus session (any desktop login).
	require("gvfs"):setup({
		which_keys = "1234567890qwertyuiopasdfghjklzxcvbnm",
		blacklist_devices = { { scheme = "file" } },
		save_path = os.getenv("HOME") .. "/.config/yazi/gvfs.private",
		save_path_automounts = os.getenv("HOME") .. "/.config/yazi/gvfs_automounts.private",
		input_position = { "center", y = 0, w = 60 },
	})

	-- recycle-bin (R b / R o / R r / R d / R e): browse and restore the trash
	-- (trash-cli).
	require("recycle-bin"):setup()
end
